import {
  IUser,
  ITraineeProfile,
  ITrainerProfile,
  ICourse,
  IAssessment,
  IEnrollment,
  ICertificate,
  ICompetency,
  ITraineeCompetency,
  ISkillGap,
  IAnnouncement,
  IFeedback,
  IRoleTemplate,
  ILearningPath,
  ITrainingEvent,
  ITrainerLibraryResource,
  INotification,
  IDepartmentSkillCoverage,
} from './types';

export const SEED_PASSWORD_HASH = '$2a$10$7ZzT2r/rIomk37V/549Q1.8wKz.hV698F53iCqYl4J2nZzUsmzG5a'; // Hash of 'Password123!'
export const DEMO_PASSWORD = 'Password123!';

// ==========================================
// 1. SEED USERS (1 Admin, 5 Trainers, 20 Trainees)
// ==========================================
export const SEED_USERS: IUser[] = [
  // Admin
  {
    _id: 'usr_admin_001',
    name: 'Dr. M. Mohapatra (Admin)',
    email: 'admin@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'admin',
    status: 'approved',
    department: 'Directorate General, IMD HQ',
    designation: 'Director General & Capacity Administrator',
    phone: '+91 11 2461 1068',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    createdAt: '2026-01-10T09:00:00Z',
  },
  // Trainers (5 Trainers)
  {
    _id: 'usr_trainer_001',
    name: 'Dr. Rajesh Sharma',
    email: 'trainer@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Numerical Weather Prediction Division',
    designation: 'Senior Meteorologist & Chief Trainer',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    _id: 'usr_trainer_002',
    name: 'Dr. Ananya Sen',
    email: 'ananya.sen@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Satellite Meteorology Division',
    designation: 'Principal Satellite Meteorologist',
    phone: '+91 98111 22334',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    _id: 'usr_trainer_003',
    name: 'Dr. Vikram Verma',
    email: 'vikram.verma@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Climate Research and Services, Pune',
    designation: 'Lead NWP Modeling Specialist',
    phone: '+91 97234 56789',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    createdAt: '2026-01-18T14:00:00Z',
  },
  {
    _id: 'usr_trainer_004',
    name: 'Dr. Sunita Rao',
    email: 'sunita.rao@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Radar Meteorology & Severe Storms Division',
    designation: 'Chief Radar Meteorologist',
    phone: '+91 98450 11223',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    createdAt: '2026-01-20T11:00:00Z',
  },
  {
    _id: 'usr_trainer_pending',
    name: 'Dr. K. Srinivas',
    email: 'srinivas.k@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'pending',
    department: 'Aviation Meteorological Cadre, New Delhi',
    designation: 'Senior Aviation Forecaster',
    phone: '+91 98102 33445',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    createdAt: '2026-03-02T11:00:00Z',
  },
  // Trainees (20 Trainees across IMD Centres)
  {
    _id: 'usr_trainee_001',
    name: 'Pooja Iyer',
    email: 'trainee@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Regional Meteorological Centre, Mumbai',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94444 12345',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    createdAt: '2026-02-01T08:30:00Z',
  },
  {
    _id: 'usr_trainee_002',
    name: 'Amitabh Mukherjee',
    email: 'amitabh.m@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Doppler Radar Station, Kolkata',
    designation: 'Meteorologist-A',
    phone: '+91 98300 45678',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    createdAt: '2026-02-05T10:15:00Z',
  },
  {
    _id: 'usr_trainee_003',
    name: 'Kavita Nair',
    email: 'kavita.nair@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Regional Meteorological Centre, Chennai',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 98401 23456',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    createdAt: '2026-02-08T09:00:00Z',
  },
  {
    _id: 'usr_trainee_004',
    name: 'Rohan Deshmukh',
    email: 'rohan.deshmukh@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Climate Research & Services, Pune',
    designation: 'Meteorologist-B',
    phone: '+91 98220 34567',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    createdAt: '2026-02-10T11:30:00Z',
  },
  {
    _id: 'usr_trainee_005',
    name: 'Meera Patel',
    email: 'meera.patel@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Ahmedabad',
    designation: 'Scientific Assistant Grade-II',
    phone: '+91 98791 45678',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    createdAt: '2026-02-12T14:20:00Z',
  },
  {
    _id: 'usr_trainee_006',
    name: 'Alok Tripathi',
    email: 'alok.tripathi@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Lucknow',
    designation: 'Assistant Meteorologist',
    phone: '+91 94150 56789',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    createdAt: '2026-02-14T10:00:00Z',
  },
  {
    _id: 'usr_trainee_007',
    name: 'Sunita Devi',
    email: 'sunita.devi@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Patna',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94310 67890',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    createdAt: '2026-02-15T09:40:00Z',
  },
  {
    _id: 'usr_trainee_008',
    name: 'Rajeshwari Raman',
    email: 'rajeshwari.r@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Bengaluru',
    designation: 'Meteorologist-A',
    phone: '+91 98450 78901',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150',
    createdAt: '2026-02-17T13:10:00Z',
  },
  {
    _id: 'usr_trainee_009',
    name: 'Deepak Joshi',
    email: 'deepak.joshi@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Dehradun',
    designation: 'Scientific Assistant Grade-II',
    phone: '+91 94120 89012',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    createdAt: '2026-02-18T15:00:00Z',
  },
  {
    _id: 'usr_trainee_010',
    name: 'Priya Sharma',
    email: 'priya.sharma@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Jaipur',
    designation: 'Assistant Meteorologist',
    phone: '+91 94140 90123',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    createdAt: '2026-02-20T11:15:00Z',
  },
  {
    _id: 'usr_trainee_011',
    name: 'Tanmoy Das',
    email: 'tanmoy.das@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Regional Meteorological Centre, Guwahati',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 98640 12345',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150',
    createdAt: '2026-02-21T10:00:00Z',
  },
  {
    _id: 'usr_trainee_012',
    name: 'Vikram Rathore',
    email: 'vikram.r@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Bhopal',
    designation: 'Meteorologist-A',
    phone: '+91 94250 23456',
    avatar: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=150',
    createdAt: '2026-02-22T14:30:00Z',
  },
  {
    _id: 'usr_trainee_013',
    name: 'Ananya Goswami',
    email: 'ananya.g@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Bhubaneswar',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94370 34567',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    createdAt: '2026-02-23T09:15:00Z',
  },
  {
    _id: 'usr_trainee_014',
    name: 'Harpreet Singh',
    email: 'harpreet.s@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Chandigarh',
    designation: 'Assistant Meteorologist',
    phone: '+91 98140 45678',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
    createdAt: '2026-02-24T12:00:00Z',
  },
  {
    _id: 'usr_trainee_015',
    name: 'Divya Menon',
    email: 'divya.menon@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Thiruvananthapuram',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94470 56789',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a171edd2521d?w=150',
    createdAt: '2026-02-25T11:45:00Z',
  },
  {
    _id: 'usr_trainee_016',
    name: 'Sandeep Reddy',
    email: 'sandeep.r@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Hyderabad',
    designation: 'Meteorologist-A',
    phone: '+91 98480 67890',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    createdAt: '2026-02-26T16:00:00Z',
  },
  {
    _id: 'usr_trainee_017',
    name: 'Neha Sengupta',
    email: 'neha.s@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Doppler Radar Station, Siliguri',
    designation: 'Scientific Assistant Grade-II',
    phone: '+91 98320 78901',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    createdAt: '2026-02-27T10:30:00Z',
  },
  {
    _id: 'usr_trainee_018',
    name: 'Suresh Choudhury',
    email: 'suresh.c@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Srinagar',
    designation: 'Assistant Meteorologist',
    phone: '+91 94190 89012',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    createdAt: '2026-02-28T09:00:00Z',
  },
  {
    _id: 'usr_trainee_019',
    name: 'Arpita Borgohain',
    email: 'arpita.b@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Agartala',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94360 90123',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    createdAt: '2026-03-01T13:20:00Z',
  },
  {
    _id: 'usr_trainee_020',
    name: 'Mohammed Rizwan',
    email: 'mohammed.r@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Meteorological Centre, Port Blair',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94342 01234',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    createdAt: '2026-03-02T10:00:00Z',
  },
];

// ==========================================
// 2. SEED PROFILES
// ==========================================
export const SEED_TRAINEE_PROFILES: ITraineeProfile[] = [
  {
    _id: 'prof_trainee_001',
    userId: 'usr_trainee_001',
    department: 'Regional Meteorological Centre, Mumbai',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94444 12345',
    bio: 'Dedicated meteorological assistant specializing in coastal radar observations, automatic weather station telemetry verification, and synoptic weather chart analysis for Arabian Sea cyclones.',
    education: [
      {
        degree: 'M.Sc. Physics (Atmospheric Science)',
        institution: 'University of Mumbai',
        qualification: 'First Class with Distinction',
        year: '2024',
      },
      {
        degree: 'B.Sc. Physics & Mathematics',
        institution: 'St. Xavier’s College, Mumbai',
        qualification: 'First Class',
        year: '2022',
      },
    ],
    experience: [
      {
        organization: 'India Meteorological Department',
        position: 'Scientific Assistant Grade-I',
        years: 2,
      },
      {
        organization: 'Indian Institute of Geomagnetism',
        position: 'Graduate Research Intern',
        years: 1,
      },
    ],
    skills: ['Surface Observation', 'AWS Telemetry', 'Tephigram Plotting', 'Python', 'Radar Echo Interpretation'],
    interests: ['Tropical Cyclogenesis', 'Nowcasting High Impact Rain', 'Numerical Modeling', 'Machine Learning in Weather'],
    completedCertificatesCount: 1,
    learningHours: 126,
    learningStreakDays: 14,
    badges: [
      '🏅 Data Analysis Practitioner',
      '🏅 50 Hours of Learning',
      '🏅 5 Courses Completed',
      '🏅 Assessment Excellence',
    ],
    updatedAt: '2026-03-01T12:00:00Z',
  },
];

export const SEED_TRAINER_PROFILES: ITrainerProfile[] = [
  {
    _id: 'prof_trainer_001',
    userId: 'usr_trainer_001',
    name: 'Dr. Rajesh Sharma',
    department: 'Numerical Weather Prediction Division',
    designation: 'Senior Meteorologist & Chief Trainer',
    bio: 'Over 18 years of operational synoptic forecasting and numerical modeling experience across IMD New Delhi and Pune. Expert trainer for WMO Tropical Cyclone Workshops.',
    experienceYears: 18,
    specializations: [
      'Synoptic Meteorology',
      'Tropical Cyclone Forecasting',
      'NWP Post-processing',
      'Radar Interpretation',
    ],
    competencies: [
      { name: 'Meteorology', domain: 'Core Meteorological Science', level: 'Expert', score: 98 },
      { name: 'Weather Forecasting', domain: 'Synoptic Operations', level: 'Expert', score: 96 },
      { name: 'Data Analysis', domain: 'Computational Meteorology', level: 'Advanced', score: 88 },
      { name: 'Numerical Weather Prediction', domain: 'Model Dynamics', level: 'Advanced', score: 92 },
      { name: 'Atmospheric Science', domain: 'Core Physics', level: 'Expert', score: 95 },
    ],
    rating: 4.9,
    totalCourses: 2,
    totalStudentsTaught: 340,
    certifications: ['WMO Senior Meteorologist Certificate', 'IMD Lead Forecaster Credential', 'ESSO Tropical Warning Fellow'],
    coursesTaught: ['Weather Forecasting Fundamentals', 'Synoptic Storm Tracking Protocols'],
  },
  {
    _id: 'prof_trainer_002',
    userId: 'usr_trainer_002',
    name: 'Dr. Ananya Sen',
    department: 'Satellite Meteorology Division',
    designation: 'Principal Satellite Meteorologist',
    bio: 'Specialist in INSAT-3DR and 3DS multi-spectral radiance interpretation, atmospheric motion vectors, Dvorak tropical cyclone intensity evaluation, and RGB channel compositing.',
    experienceYears: 14,
    specializations: [
      'INSAT-3DR Payloads',
      'Dvorak Cyclone Intensity',
      'RGB Composite Imagery',
      'Atmospheric Motion Vectors',
    ],
    competencies: [
      { name: 'Satellite Meteorology', domain: 'Earth Observation', level: 'Expert', score: 96 },
      { name: 'Meteorology', domain: 'Core Meteorological Science', level: 'Advanced', score: 90 },
      { name: 'Data Analysis', domain: 'Computational Meteorology', level: 'Advanced', score: 85 },
      { name: 'Python', domain: 'Scientific Programming', level: 'Intermediate', score: 75 },
    ],
    rating: 4.85,
    totalCourses: 1,
    totalStudentsTaught: 210,
    certifications: ['ISRO-IMD Joint Remote Sensing Fellow', 'EUMETSAT Imagery Interpretation Specialist'],
    coursesTaught: ['Satellite Meteorology', 'INSAT Multi-Spectral Data Interpretation'],
  },
  {
    _id: 'prof_trainer_003',
    userId: 'usr_trainer_003',
    name: 'Dr. Vikram Verma',
    department: 'Climate Research and Services, Pune',
    designation: 'Lead NWP Modeling Specialist',
    bio: 'Expert computational atmospheric physicist focusing on high-resolution convective scale modeling, ensemble forecasting, Python workflow automation, and NetCDF processing.',
    experienceYears: 11,
    specializations: [
      'Python for Meteorology',
      'NetCDF / GRIB2 Processing',
      'Numerical Weather Prediction',
      'Data Analysis',
    ],
    competencies: [
      { name: 'Python', domain: 'Scientific Programming', level: 'Expert', score: 98 },
      { name: 'Data Analysis', domain: 'Computational Meteorology', level: 'Expert', score: 94 },
      { name: 'Numerical Weather Prediction', domain: 'Model Dynamics', level: 'Advanced', score: 90 },
      { name: 'Climate Science', domain: 'Climatology', level: 'Advanced', score: 88 },
      { name: 'GIS', domain: 'Geospatial Analysis', level: 'Advanced', score: 86 },
    ],
    rating: 4.95,
    totalCourses: 2,
    totalStudentsTaught: 280,
    certifications: ['MetPy Certified Developer', 'NCAR WRF Modeling Specialist'],
    coursesTaught: ['Python for Meteorological Data Analysis', 'Climate Data Analysis & Extreme Weather Modeling'],
  },
  {
    _id: 'prof_trainer_004',
    userId: 'usr_trainer_004',
    name: 'Dr. Sunita Rao',
    department: 'Radar Meteorology & Severe Storms Division',
    designation: 'Chief Radar Meteorologist',
    bio: 'Expert in S-Band and C-Band Doppler Weather Radar (DWR) operations, dual-polarization hydrometeor classification, severe squall line nowcasting, and mesoscale convective vortex tracking.',
    experienceYears: 16,
    specializations: ['Doppler Radar (DWR)', 'Dual-Pol Hydrometeor Classification', 'Nowcasting', 'Severe Convection'],
    competencies: [
      { name: 'Radar Meteorology', domain: 'Remote Sensing', level: 'Expert', score: 98 },
      { name: 'Meteorology', domain: 'Core Meteorological Science', level: 'Advanced', score: 92 },
      { name: 'Weather Forecasting', domain: 'Synoptic Operations', level: 'Advanced', score: 88 },
      { name: 'Atmospheric Science', domain: 'Core Physics', level: 'Advanced', score: 89 },
    ],
    rating: 4.9,
    totalCourses: 1,
    totalStudentsTaught: 195,
    certifications: ['WMO Radar Training Lead', 'IMD DWR Network Calibration Head'],
    coursesTaught: ['Doppler Weather Radar Interpretation'],
  },
];

// ==========================================
// 3. SEED COMPETENCIES (10 Competencies)
// ==========================================
export const SEED_COMPETENCIES: ICompetency[] = [
  {
    _id: 'comp_01',
    name: 'Meteorology',
    domain: 'Core Meteorological Science',
    description: 'Fundamental principles of atmospheric thermodynamics, radiation, dynamics, hydrostatic balance, and cloud microphysics.',
    category: 'Core Science',
    icon: 'CloudSun',
    requiredLevel: 'Expert',
    relatedCourses: ['Weather Forecasting Fundamentals', 'Weather Observation & Surface Instrumentation'],
    relatedRoles: ['Weather Forecaster', 'Aviation Meteorological Officer', 'Doppler Radar Specialist'],
    targetBenchmark: 80,
  },
  {
    _id: 'comp_02',
    name: 'Weather Forecasting',
    domain: 'Synoptic Operations',
    description: 'Surface and upper-air synoptic chart interpretation, frontogenesis, cyclogenesis, nowcasting severe storms, and public weather bulletin preparation.',
    category: 'Operational Skills',
    icon: 'Compass',
    requiredLevel: 'Advanced',
    relatedCourses: ['Weather Forecasting Fundamentals'],
    relatedRoles: ['Weather Forecaster', 'Aviation Meteorological Officer'],
    targetBenchmark: 85,
  },
  {
    _id: 'comp_03',
    name: 'Climate Science',
    domain: 'Climatology',
    description: 'Long-range climate variability, ENSO, Indian Ocean Dipole (IOD), Madden-Julian Oscillation (MJO), climate normals, and IPCC assessment downscaling.',
    category: 'Climate & Research',
    icon: 'Globe',
    requiredLevel: 'Advanced',
    relatedCourses: ['Climate Data Analysis & Extreme Weather Modeling'],
    relatedRoles: ['Climate Research Modeler'],
    targetBenchmark: 70,
  },
  {
    _id: 'comp_04',
    name: 'Satellite Meteorology',
    domain: 'Earth Observation',
    description: 'Understanding geostationary & polar-orbiting satellites, INSAT-3DR visible, infrared, and water vapor channels, RGB composites, and wind vector tracking.',
    category: 'Remote Sensing',
    icon: 'Radio',
    requiredLevel: 'Advanced',
    relatedCourses: ['Satellite Meteorology'],
    relatedRoles: ['Weather Forecaster', 'Aviation Meteorological Officer'],
    targetBenchmark: 75,
  },
  {
    _id: 'comp_05',
    name: 'Data Analysis',
    domain: 'Computational Meteorology',
    description: 'Statistical analysis of meteorological time series, trend analysis, extreme value analysis, anomaly detection, and data assimilation concepts.',
    category: 'Analytics',
    icon: 'BarChart3',
    requiredLevel: 'Advanced',
    relatedCourses: ['Python for Meteorological Data Analysis', 'Climate Data Analysis & Extreme Weather Modeling'],
    relatedRoles: ['Weather Forecaster', 'Climate Research Modeler'],
    targetBenchmark: 70,
  },
  {
    _id: 'comp_06',
    name: 'Python',
    domain: 'Scientific Programming',
    description: 'Python programming using NumPy, Pandas, Xarray, MetPy, and Cartopy for atmospheric datasets, automated alert generation, and GIS contouring.',
    category: 'Programming',
    icon: 'Code',
    requiredLevel: 'Intermediate',
    relatedCourses: ['Python for Meteorological Data Analysis'],
    relatedRoles: ['Weather Forecaster', 'Climate Research Modeler'],
    targetBenchmark: 65,
  },
  {
    _id: 'comp_07',
    name: 'Numerical Weather Prediction',
    domain: 'Model Dynamics',
    description: 'Governing primitive equations, grid systems, boundary conditions, parameterization schemes, and multi-model ensemble consensus forecasting.',
    category: 'Modeling',
    icon: 'Cpu',
    requiredLevel: 'Advanced',
    relatedCourses: ['Weather Forecasting Fundamentals', 'Python for Meteorological Data Analysis'],
    relatedRoles: ['Climate Research Modeler', 'Weather Forecaster'],
    targetBenchmark: 75,
  },
  {
    _id: 'comp_08',
    name: 'Radar Meteorology',
    domain: 'Remote Sensing',
    description: 'Doppler Weather Radar (DWR) reflectivity, radial velocity, spectral width, dual-pol hydrometeor classification, and nowcasting convective squall lines.',
    category: 'Remote Sensing',
    icon: 'Activity',
    requiredLevel: 'Advanced',
    relatedCourses: ['Weather Observation & Surface Instrumentation'],
    relatedRoles: ['Doppler Radar Specialist', 'Aviation Meteorological Officer'],
    targetBenchmark: 80,
  },
  {
    _id: 'comp_09',
    name: 'GIS',
    domain: 'Geospatial Analysis',
    description: 'Geospatial mapping of meteorological hazard zones, flood inundation modeling, spatial interpolation of rainfall, and QGIS layer integration.',
    category: 'Geospatial Analysis',
    icon: 'Layers',
    requiredLevel: 'Intermediate',
    relatedCourses: ['Python for Meteorological Data Analysis'],
    relatedRoles: ['Climate Research Modeler'],
    targetBenchmark: 65,
  },
  {
    _id: 'comp_10',
    name: 'Atmospheric Science',
    domain: 'Core Physics',
    description: 'Thermodynamics of dry and moist air, hydrostatic and hypsometric relations, radiative transfer, planetary boundary layer dynamics, and cloud physics.',
    category: 'Core Physics',
    icon: 'Wind',
    requiredLevel: 'Advanced',
    relatedCourses: ['Weather Forecasting Fundamentals', 'Weather Observation & Surface Instrumentation'],
    relatedRoles: ['Weather Forecaster', 'Doppler Radar Specialist', 'Climate Research Modeler'],
    targetBenchmark: 75,
  },
];

// ==========================================
// 4. SEED ROLE TEMPLATES (Feature 2)
// ==========================================
export const SEED_ROLE_TEMPLATES: IRoleTemplate[] = [
  {
    _id: 'role_01',
    name: 'Weather Forecaster',
    code: 'WF-CORE',
    department: 'Synoptic Forecasting Operations',
    description:
      'Responsible for synoptic weather charts, cyclogenesis monitoring, issuing heavy rainfall warnings, and preparation of operational weather bulletins across regional meteorological centres.',
    requiredCompetencies: [
      { competencyName: 'Meteorology', requiredScore: 80, requiredLevel: 'Advanced' },
      { competencyName: 'Weather Forecasting', requiredScore: 85, requiredLevel: 'Advanced' },
      { competencyName: 'Data Analysis', requiredScore: 70, requiredLevel: 'Intermediate' },
      { competencyName: 'Python', requiredScore: 60, requiredLevel: 'Intermediate' },
      { competencyName: 'Satellite Meteorology', requiredScore: 70, requiredLevel: 'Intermediate' },
    ],
    recommendedCourseIds: ['course_001', 'course_002', 'course_003'],
    disclaimer:
      'This competency matrix is for training recommendations only. Not for employment, promotion, or disciplinary decisions.',
  },
  {
    _id: 'role_02',
    name: 'Doppler Radar Specialist',
    code: 'RAD-SPEC',
    department: 'Radar Meteorology & Remote Sensing',
    description:
      'Operates S/C-band Doppler Weather Radars, monitors convective storm cells, prepares real-time severe weather nowcasts, and conducts hydrometeor dual-polarization analyses.',
    requiredCompetencies: [
      { competencyName: 'Radar Meteorology', requiredScore: 85, requiredLevel: 'Advanced' },
      { competencyName: 'Atmospheric Science', requiredScore: 75, requiredLevel: 'Advanced' },
      { competencyName: 'Weather Forecasting', requiredScore: 70, requiredLevel: 'Intermediate' },
      { competencyName: 'Data Analysis', requiredScore: 65, requiredLevel: 'Intermediate' },
    ],
    recommendedCourseIds: ['course_004', 'course_001'],
    disclaimer:
      'This competency matrix is for training recommendations only. Not for employment, promotion, or disciplinary decisions.',
  },
  {
    _id: 'role_03',
    name: 'Climate Research Modeler',
    code: 'CLM-MOD',
    department: 'Climate Research and Services',
    description:
      'Analyzes long-term climate datasets, conducts extreme weather return period modeling, downscales global climate models, and prepares seasonal climate outlooks.',
    requiredCompetencies: [
      { competencyName: 'Climate Science', requiredScore: 85, requiredLevel: 'Advanced' },
      { competencyName: 'Data Analysis', requiredScore: 80, requiredLevel: 'Advanced' },
      { competencyName: 'Python', requiredScore: 75, requiredLevel: 'Advanced' },
      { competencyName: 'Numerical Weather Prediction', requiredScore: 70, requiredLevel: 'Intermediate' },
    ],
    recommendedCourseIds: ['course_005', 'course_003'],
    disclaimer:
      'This competency matrix is for training recommendations only. Not for employment, promotion, or disciplinary decisions.',
  },
  {
    _id: 'role_04',
    name: 'Aviation Weather Officer',
    code: 'AV-MET',
    department: 'Aviation Meteorological Services',
    description:
      'Issues Aerodrome Forecasts (TAF), METAR/SPECI reports, SIGMET advisories for en-route turbulence, icing, and low-level wind shear for airport flight safety.',
    requiredCompetencies: [
      { competencyName: 'Weather Forecasting', requiredScore: 80, requiredLevel: 'Advanced' },
      { competencyName: 'Meteorology', requiredScore: 80, requiredLevel: 'Advanced' },
      { competencyName: 'Radar Meteorology', requiredScore: 75, requiredLevel: 'Intermediate' },
      { competencyName: 'Satellite Meteorology', requiredScore: 70, requiredLevel: 'Intermediate' },
    ],
    recommendedCourseIds: ['course_001', 'course_002', 'course_004'],
    disclaimer:
      'This competency matrix is for training recommendations only. Not for employment, promotion, or disciplinary decisions.',
  },
];

// ==========================================
// 5. SEED TRAINEE COMPETENCIES (Pooja Iyer)
// ==========================================
export const SEED_TRAINEE_COMPETENCIES: ITraineeCompetency[] = [
  {
    _id: 'tc_01',
    traineeId: 'usr_trainee_001',
    competencyName: 'Meteorology',
    domain: 'Core Meteorological Science',
    level: 'Advanced',
    score: 85,
    lastUpdated: '2026-02-20T10:00:00Z',
  },
  {
    _id: 'tc_02',
    traineeId: 'usr_trainee_001',
    competencyName: 'Weather Forecasting',
    domain: 'Synoptic Operations',
    level: 'Beginner',
    score: 45, // GAP: Required is 85%, Current is 45% -> Gap is 40% (or 35% depending on benchmark)
    lastUpdated: '2026-01-25T11:00:00Z',
  },
  {
    _id: 'tc_03',
    traineeId: 'usr_trainee_001',
    competencyName: 'Python',
    domain: 'Scientific Programming',
    level: 'Intermediate',
    score: 72,
    lastUpdated: '2026-03-01T15:30:00Z',
  },
  {
    _id: 'tc_04',
    traineeId: 'usr_trainee_001',
    competencyName: 'Data Analysis',
    domain: 'Computational Meteorology',
    level: 'Intermediate',
    score: 60,
    lastUpdated: '2026-02-15T09:15:00Z',
  },
  {
    _id: 'tc_05',
    traineeId: 'usr_trainee_001',
    competencyName: 'Satellite Meteorology',
    domain: 'Earth Observation',
    level: 'Beginner',
    score: 50,
    lastUpdated: '2026-01-10T12:00:00Z',
  },
  {
    _id: 'tc_06',
    traineeId: 'usr_trainee_001',
    competencyName: 'Climate Science',
    domain: 'Climatology',
    level: 'Intermediate',
    score: 55,
    lastUpdated: '2026-02-05T14:00:00Z',
  },
  {
    _id: 'tc_07',
    traineeId: 'usr_trainee_001',
    competencyName: 'Numerical Weather Prediction',
    domain: 'Model Dynamics',
    level: 'Beginner',
    score: 48,
    lastUpdated: '2026-01-20T08:00:00Z',
  },
  {
    _id: 'tc_08',
    traineeId: 'usr_trainee_001',
    competencyName: 'Radar Meteorology',
    domain: 'Remote Sensing',
    level: 'Intermediate',
    score: 62,
    lastUpdated: '2026-02-18T10:00:00Z',
  },
  {
    _id: 'tc_09',
    traineeId: 'usr_trainee_001',
    competencyName: 'GIS',
    domain: 'Geospatial Analysis',
    level: 'Beginner',
    score: 45,
    lastUpdated: '2026-01-15T10:00:00Z',
  },
  {
    _id: 'tc_10',
    traineeId: 'usr_trainee_001',
    competencyName: 'Atmospheric Science',
    domain: 'Core Physics',
    level: 'Advanced',
    score: 82,
    lastUpdated: '2026-02-25T11:00:00Z',
  },
];

// ==========================================
// 6. SEED SKILL GAPS
// ==========================================
export const SEED_SKILL_GAPS: ISkillGap[] = [
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Weather Forecasting',
    currentScore: 45,
    requiredScore: 80,
    gap: 35,
    status: 'Critical',
    recommendedCourseIds: ['course_001'],
    explanation:
      'These courses address competencies where your current level is below the selected role requirement.',
    recommendedCourses: [
      {
        id: 'course_001',
        title: 'Weather Forecasting Fundamentals',
        difficulty: 'Beginner',
        duration: '4 Weeks',
      },
    ],
  },
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Satellite Meteorology',
    currentScore: 50,
    requiredScore: 70,
    gap: 20,
    status: 'Moderate',
    recommendedCourseIds: ['course_002'],
    explanation:
      'These courses address competencies where your current level is below the selected role requirement.',
    recommendedCourses: [
      {
        id: 'course_002',
        title: 'Satellite Meteorology',
        difficulty: 'Intermediate',
        duration: '5 Weeks',
      },
    ],
  },
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Data Analysis',
    currentScore: 60,
    requiredScore: 70,
    gap: 10,
    status: 'Moderate',
    recommendedCourseIds: ['course_003'],
    explanation:
      'These courses address competencies where your current level is below the selected role requirement.',
    recommendedCourses: [
      {
        id: 'course_003',
        title: 'Python for Meteorological Data Analysis',
        difficulty: 'Intermediate',
        duration: '4 Weeks',
      },
    ],
  },
];

// ==========================================
// 7. SEED COURSES (5 Complete Courses)
// ==========================================
export const SEED_COURSES: ICourse[] = [
  {
    _id: 'course_001',
    title: 'Weather Forecasting Fundamentals',
    slug: 'weather-forecasting-fundamentals',
    description:
      'A foundational certification course covering atmospheric dynamics, synoptic chart analysis, observation station procedures, and basic weather forecasting protocols used across IMD forecasting centers.',
    category: 'Synoptic Meteorology & Forecasting',
    difficulty: 'Beginner',
    duration: '4 Weeks (20 Hours)',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    trainerRole: 'Senior Meteorologist & Chief Trainer',
    thumbnail: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Synoptic', 'Forecast', 'Observation', 'Atmospheric Physics'],
    enrolledCount: 84,
    rating: 4.9,
    ratingCount: 38,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Weather Forecasting',
    competencyGainPercentage: 28, // increases from 45% to 73%
    preAssessmentId: 'pre_assess_001',
    assessmentId: 'assess_001',
    prerequisites: ['Weather Observation & Surface Instrumentation'],
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-15T12:00:00Z',
    modules: [
      {
        id: 'mod_1_1',
        title: 'Module 1: Introduction to Meteorology',
        description: 'Atmospheric layers, solar radiation budget, temperature profiles, and barometric pressure laws.',
        order: 1,
        lessons: [
          {
            id: 'les_1_1_1',
            title: '1.1 Composition and Structure of the Atmosphere',
            description: 'Exploration of troposphere, stratosphere, mesosphere, and thermosphere with lapse rate calculations.',
            order: 1,
            duration: '25 mins',
            type: 'article',
            contentBody: `### Atmospheric Layers & Vertical Thermal Profiles\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nEarth's atmosphere is divided into distinct thermal strata based on temperature lapse rate gradients:\n\n1. **Troposphere**: Extends from ground to ~16-18 km in tropical regions (such as India) and ~8 km at poles. Characterized by average environmental lapse rate of 6.5°C/km. Nearly all convective weather, clouds, cyclones, and monsoon troughs occur within this sphere.\n2. **Tropopause**: Inversion boundary acting as a lid to vertical convection, crucial for identifying jet stream cores.\n3. **Stratosphere**: Extends to ~50 km where ozone absorption of UV generates positive thermal inversion.\n\n#### Key Formula:\nHydrostatic Equation: $dP = -\\rho g dz = -\\frac{P g}{R_d T} dz$\nIntegrating gives the hypsometric equation for geopotential thickness between pressure surfaces.`,
            resources: [
              {
                id: 'res_1_1',
                title: 'Atmospheric Layers Reference Guide.pdf',
                type: 'pdf',
                fileUrl: '/docs/atmospheric_layers_reference.pdf',
                fileSize: '1.4 MB',
              },
            ],
          },
          {
            id: 'les_1_1_2',
            title: '1.2 Atmospheric Pressure & Wind Dynamics',
            description: 'Pressure gradient force, Coriolis acceleration, geostrophic and gradient wind approximations.',
            order: 2,
            duration: '35 mins',
            type: 'video',
            contentUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            contentBody: `### Forces Governing Atmospheric Motion\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nIn meteorological coordinate systems, horizontal air parcels are governed by:\n- **Pressure Gradient Force (PGF)**: Directs from high to low pressure perpendicular to isobars.\n- **Coriolis Force ($f = 2\\Omega \\sin\\phi$)**: Deflects winds to the right in Northern Hemisphere and left in Southern Hemisphere.\n- **Friction Force**: Significant in planetary boundary layer (PBL) below 1 km, causing cross-isobaric inward flow into low-pressure centers (convergence) and outward flow from highs (divergence).`,
          },
        ],
      },
      {
        id: 'mod_1_2',
        title: 'Module 2: Weather Observation Systems',
        description: 'Surface meteorological instruments, AWS (Automatic Weather Stations), radiosonde soundings, and Doppler radars.',
        order: 2,
        lessons: [
          {
            id: 'les_1_2_1',
            title: '2.1 Surface Instruments & Stevenson Screen Protocols',
            description: 'Standard exposure, dry/wet bulb thermometers, barometers, anemometers, and rain gauges.',
            order: 1,
            duration: '30 mins',
            type: 'presentation',
            contentBody: `### Standard IMD Surface Meteorological Observation Protocol\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n#### Routine Synoptic Hours:\nObservations are recorded at UTC standard synoptic intervals (00, 03, 06, 09, 12, 15, 18, 21 UTC) corresponding to 0530, 0830, 1130, 1430, 1730, 2030, 2330, and 0230 IST.\n\n#### Instrument Checks:\n- **Stevenson Screen**: Double-louvered white screen mounted at 1.25 m above natural turf surface.\n- **Dry & Wet Bulb**: Psychrometric formula yields dew point temperature and relative humidity.\n- **Barometer Reduction**: Reducing station level pressure (QFE) to Mean Sea Level (MSL / QFF) via hypsometric reduction tables.`,
          },
          {
            id: 'les_1_2_2',
            title: '2.2 Automatic Weather Station (AWS) & Radiosonde Tephigrams',
            description: 'Upper air thermodynamic diagrams (Tephigram) plotting and instability index evaluation (CAPE, CIN).',
            order: 2,
            duration: '40 mins',
            type: 'article',
            contentBody: `### Tephigram Analysis & Convective Instability\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nThe Tephigram ($T-\\phi$ gram, temperature and entropy) is IMD's standard thermodynamic chart.\n\n#### Severe Weather Parameters:\n- **LCL (Lifting Condensation Level)**: Base of convective clouds.\n- **LFC (Level of Free Convection)**: Point where parcel temperature exceeds ambient environment.\n- **CAPE (Convective Available Potential Energy)**: $> 1500$ J/kg indicates moderate to severe thunderstorm potential.\n- **CIN (Convective Inhibition)**: Barrier energy required to be overcome by diurnal solar heating or low-level convergence.`,
          },
        ],
      },
      {
        id: 'mod_1_3',
        title: 'Module 3: Forecasting Basics',
        description: 'Synoptic charts, trough lines, cyclonic circulations, jet streams, and monsoon depressions.',
        order: 3,
        lessons: [
          {
            id: 'les_1_3_1',
            title: '3.1 Synoptic Chart Plotting & Frontal/Tropical Systems',
            description: 'Station model plots, isobaric drawing at 2 hPa intervals, and streamline/isotach analysis.',
            order: 1,
            duration: '45 mins',
            type: 'article',
            contentBody: `### Synoptic Weather Chart Analysis Procedures\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nIn tropical meteorology, pressure gradients are typically weak compared to mid-latitudes, making streamline analysis and moisture convergence charts essential.\n\n1. Plot surface reports using standard WMO station models: wind barb, cloud amount in oktas, present weather symbols ($ww$), barometric tendency.\n2. Trace the Monsoon Trough line extending from Ganganagar to Kolkata and the Head Bay of Bengal.\n3. Identify Embedded Cyclonic Circulations ($cycir$) at 0.9 km, 1.5 km, 3.1 km, and 5.8 km a.s.l. levels.`,
          },
        ],
      },
      {
        id: 'mod_1_4',
        title: 'Module 4: Weather Data Interpretation',
        description: 'Synthesizing radar reflectivity, satellite infrared bands, and NWP model guidance into actionable bulletins.',
        order: 4,
        lessons: [
          {
            id: 'les_1_4_1',
            title: '4.1 Integrating Radar, Satellite & NWP Guidance',
            description: 'Step-by-step methodology for severe weather warnings and public impact-based forecasts.',
            order: 1,
            duration: '35 mins',
            type: 'article',
            contentBody: `### Integrated Weather Forecasting Protocol\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nForecasters cross-examine:\n- **Satellite IR/WV loops**: Cloud top brightness temperature ($-60^\\circ$C signifies deep convection).\n- **Doppler Weather Radar (DWR)**: MAX(Z), Plan Position Indicator (PPI), Velocity Azimuth Display (VAD).\n- **Ensemble NWP Outputs**: GFS-T1534, NCUM, and WRF 3km hourly meteograms.`,
          },
        ],
      },
    ],
  },
  {
    _id: 'course_002',
    title: 'Satellite Meteorology',
    slug: 'satellite-meteorology',
    description:
      'Comprehensive study of meteorological satellites with specialized focus on INSAT-3D, 3DR, and 3DS payloads, radiance channels, RGB composite generation, and cyclogenesis monitoring.',
    category: 'Remote Sensing & Earth Observation',
    difficulty: 'Intermediate',
    duration: '5 Weeks (25 Hours)',
    trainerId: 'usr_trainer_002',
    trainerName: 'Dr. Ananya Sen',
    trainerRole: 'Principal Satellite Meteorologist',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Satellite', 'INSAT', 'Remote Sensing', 'Infrared', 'Cyclone'],
    enrolledCount: 62,
    rating: 4.85,
    ratingCount: 29,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Satellite Meteorology',
    competencyGainPercentage: 35,
    assessmentId: 'assess_002',
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-02-28T14:00:00Z',
    modules: [
      {
        id: 'mod_2_1',
        title: 'Module 1: Introduction to Weather Satellites',
        description: 'Orbits (Geostationary vs Polar Sun-Synchronous), Keplerian elements, resolution, and sensor payloads.',
        order: 1,
        lessons: [
          {
            id: 'les_2_1_1',
            title: '1.1 Geostationary vs Polar Orbiting Satellites',
            description: 'INSAT series stationed at 74°E and 82°E vs NOAA/MetOp polar platforms.',
            order: 1,
            duration: '30 mins',
            type: 'article',
            contentBody: `### Orbital Mechanics in Meteorological Satellite Systems\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n- **Geostationary Orbit (GEO)**: ~35,786 km altitude directly above the equator. Orbit period matches Earth's rotation (23h 56m 4s). Fixed sub-satellite point provides continuous hemispheric disc viewing at 15-minute or rapid-scan 4-minute intervals.\n- **Low Earth Sun-Synchronous Orbit (LEO)**: ~800 km altitude, inclined at ~98°. Passes over points at approximately the same local solar time, providing high spatial resolution soundings and microwave scatterometer ocean surface winds.`,
          },
        ],
      },
    ],
  },
  {
    _id: 'course_003',
    title: 'Python for Meteorological Data Analysis',
    slug: 'python-for-meteorological-data-analysis',
    description:
      'Hands-on computational training in Python for weather and climate scientists. Master NumPy, Xarray, NetCDF, GRIB2, MetPy thermodynamic plots, and automated geospatial map rendering.',
    category: 'Computational Meteorology & GIS',
    difficulty: 'Intermediate',
    duration: '4 Weeks (20 Hours)',
    trainerId: 'usr_trainer_003',
    trainerName: 'Dr. Vikram Verma',
    trainerRole: 'Lead NWP Modeling Specialist',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Python', 'NetCDF', 'Xarray', 'MetPy', 'Cartopy', 'Data Science'],
    enrolledCount: 110,
    rating: 4.95,
    ratingCount: 45,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Python',
    competencyGainPercentage: 25,
    assessmentId: 'assess_003',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    modules: [
      {
        id: 'mod_3_1',
        title: 'Module 1: Python Fundamentals for Atmospheric Sciences',
        description: 'Python environment setup, Conda, Jupyter, array broadcasting, and vectorized operations.',
        order: 1,
        lessons: [
          {
            id: 'les_3_1_1',
            title: '1.1 Scientific Python Stack & Array Operations',
            description: 'NumPy dimensional slicing, NaN mask handling, and unit conversions.',
            order: 1,
            duration: '25 mins',
            type: 'article',
            contentBody: `### NumPy in Meteorological Calculations\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nHandling 4D atmospheric datasets $(time, level, latitude, longitude)$ requires efficient array broadcasting:\n\n\`\`\`python\nimport numpy as np\n\n# Convert Celsius to Kelvin\ntemp_c = np.array([28.4, 30.1, 25.6, 22.0])\ntemp_k = temp_c + 273.15\n\n# Mask missing AWS precipitation records (-999.0)\nprecip = np.array([12.5, -999.0, 45.0, 0.0, -999.0])\nclean_precip = np.where(precip == -999.0, np.nan, precip)\nprint("Mean Daily Rainfall:", np.nanmean(clean_precip), "mm")\n\`\`\``,
          },
        ],
      },
    ],
  },
  {
    _id: 'course_004',
    title: 'Weather Observation & Surface Instrumentation',
    slug: 'weather-observation-and-surface-instrumentation',
    description:
      'Standard operating procedures for manned surface observatories and automated telemetry networks. Calibration of Stevenson screen thermometers, Fortin barometers, and tipping bucket AWS.',
    category: 'Instruments & Observational Networks',
    difficulty: 'Beginner',
    duration: '3 Weeks (15 Hours)',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    trainerRole: 'Senior Meteorologist & Chief Trainer',
    thumbnail: 'https://images.unsplash.com/photo-1590055531615-f16d36ffe8ec?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Observation', 'AWS', 'Stevenson Screen', 'Instruments', 'Barometer'],
    enrolledCount: 76,
    rating: 4.88,
    ratingCount: 31,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Meteorology',
    competencyGainPercentage: 20,
    assessmentId: 'assess_004',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z',
    modules: [
      {
        id: 'mod_4_1',
        title: 'Module 1: Surface Observatory Architecture',
        description: 'Station siting guidelines, horizon clearance, soil exposure, and enclosure standards.',
        order: 1,
        lessons: [
          {
            id: 'les_4_1_1',
            title: '1.1 Siting and Exposure Criteria for Surface Stations',
            description: 'Distance to obstructions, natural turf maintenance, and anemometer mast height standards (10m).',
            order: 1,
            duration: '30 mins',
            type: 'article',
            contentBody: `### WMO/IMD Surface Meteorological Station Siting\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n1. Sited on level ground covered with natural turf, unobstructed by buildings, trees, or steep slopes.\n2. Obstacles must be at a distance of at least twice the height of the obstacle (preferably 4 to 10 times).\n3. Wind sensors mounted at standard 10 meters a.g.l. with true north alignment check.`,
          },
        ],
      },
    ],
  },
  {
    _id: 'course_005',
    title: 'Climate Data Analysis & Extreme Weather Modeling',
    slug: 'climate-data-analysis-and-extreme-weather-modeling',
    description:
      'Rigorous statistical climatology covering extreme value distributions (GEV/Gumbel), return period estimation for 100-year floods, heatwave thresholds, and trend analysis on 50-year IMD gridded series.',
    category: 'Climatology & Statistical Modeling',
    difficulty: 'Advanced',
    duration: '6 Weeks (30 Hours)',
    trainerId: 'usr_trainer_003',
    trainerName: 'Dr. Vikram Verma',
    trainerRole: 'Lead NWP Modeling Specialist',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Climate', 'GEV', 'Extreme Weather', 'Trends', 'Monsoon'],
    enrolledCount: 45,
    rating: 4.92,
    ratingCount: 22,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Climate Science',
    competencyGainPercentage: 30,
    assessmentId: 'assess_005',
    prerequisites: ['Python for Meteorological Data Analysis', 'Weather Observation & Surface Instrumentation'],
    createdAt: '2026-02-15T11:00:00Z',
    updatedAt: '2026-03-01T15:00:00Z',
    modules: [
      {
        id: 'mod_5_1',
        title: 'Module 1: Extreme Value Theory in Meteorology',
        description: 'Generalized Extreme Value (GEV) distribution for maximum annual daily rainfall series.',
        order: 1,
        lessons: [
          {
            id: 'les_5_1_1',
            title: '1.1 Fitting GEV Distributions to Daily Maximum Rainfall',
            description: 'Location, scale, and shape parameter estimation using L-moments.',
            order: 1,
            duration: '45 mins',
            type: 'article',
            contentBody: `### Extreme Value Theory for Return Level Calculation\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nCumulative distribution function of GEV:\n$$G(z) = \\exp\\left(-\\left[1 + \\xi\\left(\\frac{z - \\mu}{\\sigma}\\right)\\right]^{-1/\\xi}\\right)$$\nwhere $\\mu$ is location, $\\sigma$ is scale, and $\\xi$ is shape parameter.\n- $\\xi = 0$: Gumbel (Type I light tail)\n- $\\xi > 0$: Frechet (Type II heavy tail)\n- $\\xi < 0$: Weibull (Type III bounded upper tail)`,
          },
        ],
      },
    ],
  },
];

// ==========================================
// 8. SEED ASSESSMENTS (Pre and Post)
// ==========================================
export const SEED_ASSESSMENTS: IAssessment[] = [
  // Pre-Assessment for Course 1 (Feature 6)
  {
    _id: 'pre_assess_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    title: 'Pre-Assessment: Weather Forecasting Fundamentals (Diagnostic Baseline)',
    description:
      'Mandatory baseline diagnostic test evaluating your incoming knowledge before beginning the course. Used to track individual competency progression.',
    durationMinutes: 20,
    totalMarks: 5,
    passingPercentage: 40,
    assessmentType: 'pre',
    status: 'published',
    createdAt: '2026-01-20T10:00:00Z',
    questions: [
      {
        id: 'pre_q_1_1',
        questionText: 'What is the average standard environmental lapse rate in the troposphere?',
        options: ['9.8 °C per km', '6.5 °C per km', '3.2 °C per km', '1.0 °C per km'],
        correctAnswerIndex: 1,
        explanation: 'The International Standard Atmosphere defines tropospheric lapse rate as 6.5 °C/km.',
        marks: 1,
      },
      {
        id: 'pre_q_1_2',
        questionText: 'In which direction does the Coriolis force deflect air parcels in the Northern Hemisphere?',
        options: ['Equatorward', 'Left of motion', 'Right of motion', 'Straight upward'],
        correctAnswerIndex: 2,
        explanation: 'Coriolis force deflects moving air parcels to their right in Northern Hemisphere.',
        marks: 1,
      },
      {
        id: 'pre_q_1_3',
        questionText: 'What standard parameter is plotted on the horizontal axis of an IMD Tephigram?',
        options: ['Entropy / Log Temperature', 'Geopotential Height', 'Wind Speed', 'Relative Humidity'],
        correctAnswerIndex: 0,
        explanation: 'The Tephigram plots Temperature (T) and Entropy (phi).',
        marks: 1,
      },
      {
        id: 'pre_q_1_4',
        questionText: 'What does a high CAPE value (> 2000 J/kg) indicate?',
        options: ['Dense fog', 'Severe thunderstorm potential', 'Stable dry atmosphere', 'High barometric pressure'],
        correctAnswerIndex: 1,
        explanation: 'High CAPE indicates large convective potential energy available for severe storms.',
        marks: 1,
      },
      {
        id: 'pre_q_1_5',
        questionText: 'What 24-hr rainfall amount is classified by IMD as "Very Heavy Rain"?',
        options: ['15.6 - 64.4 mm', '64.5 - 115.5 mm', '115.6 - 204.4 mm', '>= 204.5 mm'],
        correctAnswerIndex: 2,
        explanation: 'Very Heavy Rain is officially 115.6 to 204.4 mm in 24 hours.',
        marks: 1,
      },
    ],
  },
  // Post-Assessment for Course 1 (Feature 7)
  {
    _id: 'assess_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    title: 'Final Post-Assessment: Weather Forecasting Fundamentals',
    description:
      'Comprehensive final examination evaluating mastery of synoptic chart analysis, thermodynamic tephigrams, and forecasting SOPs.',
    durationMinutes: 20,
    totalMarks: 5,
    passingPercentage: 60,
    assessmentType: 'post',
    status: 'published',
    createdAt: '2026-01-25T12:00:00Z',
    questions: [
      {
        id: 'q_1_1',
        questionText: 'What is the average standard environmental temperature lapse rate in the troposphere?',
        options: ['9.8 °C per kilometer', '6.5 °C per kilometer', '3.2 °C per kilometer', '1.0 °C per kilometer'],
        correctAnswerIndex: 1,
        explanation: 'The International Standard Atmosphere defines tropospheric lapse rate as 6.5 °C/km.',
        marks: 1,
      },
      {
        id: 'q_1_2',
        questionText: 'In the Northern Hemisphere, which direction does the Coriolis force deflect moving air parcels?',
        options: [
          'Directly towards the equator',
          'To the left of the direction of motion',
          'To the right of the direction of motion',
          'Directly upward into the stratosphere',
        ],
        correctAnswerIndex: 2,
        explanation: 'Deflects air parcels to their right in the Northern Hemisphere.',
        marks: 1,
      },
      {
        id: 'q_1_3',
        questionText: 'At standard IMD surface meteorological observatories, what is the standard height of a Stevenson Screen thermometer bulb above the ground?',
        options: ['0.5 meters', '1.25 to 1.5 meters', '3.0 meters', '5.0 meters'],
        correctAnswerIndex: 1,
        explanation: 'Thermometer bulbs inside the Stevenson Screen are positioned between 1.25 and 1.5 meters.',
        marks: 1,
      },
      {
        id: 'q_1_4',
        questionText: 'What does a high CAPE (Convective Available Potential Energy) value exceeding 2000 J/kg on a Tephigram signify?',
        options: [
          'Dry, stable atmosphere with no cloud formation',
          'High potential for severe convective thunderstorms and squall lines',
          'Presence of dense radiation fog',
          'Persistent stratospheric ozone depletion',
        ],
        correctAnswerIndex: 1,
        explanation: 'CAPE > 2000 J/kg indicates strong atmospheric instability.',
        marks: 1,
      },
      {
        id: 'q_1_5',
        questionText: 'According to IMD criteria, 24-hour rainfall accumulation of 150.0 mm at a station is officially categorized as:',
        options: ['Moderate Rain', 'Heavy Rain', 'Very Heavy Rain', 'Extremely Heavy Rain'],
        correctAnswerIndex: 2,
        explanation: 'IMD rainfall classification: 115.6 - 204.4 mm is Very Heavy Rain.',
        marks: 1,
      },
    ],
  },
  {
    _id: 'assess_002',
    courseId: 'course_002',
    courseTitle: 'Satellite Meteorology',
    trainerId: 'usr_trainer_002',
    trainerName: 'Dr. Ananya Sen',
    title: 'Evaluation Exam: Satellite Meteorology & INSAT Payloads',
    description: 'Assessment covering geostationary orbits, infrared brightness temperatures, and Dvorak cyclone analysis.',
    durationMinutes: 20,
    totalMarks: 4,
    passingPercentage: 60,
    assessmentType: 'post',
    status: 'published',
    createdAt: '2026-02-15T10:00:00Z',
    questions: [
      {
        id: 'q_2_1',
        questionText: 'What is the approximate altitude of a Geostationary Earth Orbit (GEO) meteorological satellite?',
        options: ['800 km', '12,000 km', '35,786 km', '100,000 km'],
        correctAnswerIndex: 2,
        explanation: 'Geostationary altitude is approximately 35,786 km above Earth equator.',
        marks: 1,
      },
      {
        id: 'q_2_2',
        questionText: 'Which INSAT-3DR channel is most effective for nighttime fog and low-stratus cloud detection?',
        options: ['Visible Channel (0.65 µm)', 'TIR1 minus MIR (10.8 µm - 3.9 µm)', 'Water Vapor Channel (6.7 µm)', 'UV Ozone Channel'],
        correctAnswerIndex: 1,
        explanation: 'Differential brightness temperature between 10.8 and 3.9 microns highlights water cloud emissivity variance.',
        marks: 1,
      },
    ],
  },
  {
    _id: 'assess_003',
    courseId: 'course_003',
    courseTitle: 'Python for Meteorological Data Analysis',
    trainerId: 'usr_trainer_003',
    trainerName: 'Dr. Vikram Verma',
    title: 'Certification Quiz: Python & Scientific NetCDF Workflows',
    description: 'Practical assessment on multidimensional arrays, Xarray coordinate slicing, and Cartopy synoptic plotting.',
    durationMinutes: 25,
    totalMarks: 4,
    passingPercentage: 60,
    assessmentType: 'post',
    status: 'published',
    createdAt: '2026-02-25T11:00:00Z',
    questions: [
      {
        id: 'q_3_1',
        questionText: 'Which Python library is the standard open-source package for N-dimensional labelled array operations on NetCDF weather files?',
        options: ['Flask', 'Xarray', 'BeautifulSoup', 'Tkinter'],
        correctAnswerIndex: 1,
        explanation: 'Xarray introduces labels in the form of dimensions, coordinates, and attributes on top of raw NumPy-like arrays.',
        marks: 1,
      },
    ],
  },
  {
    _id: 'assess_004',
    courseId: 'course_004',
    courseTitle: 'Weather Observation & Surface Instrumentation',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    title: 'Practical Assessment: Surface Observation Protocols',
    description: 'Exam on Stevenson screens, barometer corrections, and AWS calibration checks.',
    durationMinutes: 20,
    totalMarks: 4,
    passingPercentage: 60,
    assessmentType: 'post',
    status: 'published',
    createdAt: '2026-02-05T10:00:00Z',
    questions: [
      {
        id: 'q_4_1',
        questionText: 'What is the standard IMD mast height for surface wind speed anemometers?',
        options: ['2 meters', '5 meters', '10 meters', '25 meters'],
        correctAnswerIndex: 2,
        explanation: 'WMO standard for surface wind measurement is 10 meters above ground in open exposure.',
        marks: 1,
      },
    ],
  },
  {
    _id: 'assess_005',
    courseId: 'course_005',
    courseTitle: 'Climate Data Analysis & Extreme Weather Modeling',
    trainerId: 'usr_trainer_003',
    trainerName: 'Dr. Vikram Verma',
    title: 'Evaluation Exam: Extreme Value Climatology',
    description: 'Assessment on GEV distributions, return periods, and trend significance tests.',
    durationMinutes: 30,
    totalMarks: 4,
    passingPercentage: 60,
    assessmentType: 'post',
    status: 'published',
    createdAt: '2026-03-01T12:00:00Z',
    questions: [
      {
        id: 'q_5_1',
        questionText: 'In the Generalized Extreme Value (GEV) distribution, what type of distribution corresponds to shape parameter xi = 0?',
        options: ['Gumbel distribution', 'Frechet distribution', 'Weibull distribution', 'Normal distribution'],
        correctAnswerIndex: 0,
        explanation: 'When xi = 0, the GEV distribution reduces to the Gumbel (Type I) distribution.',
        marks: 1,
      },
    ],
  },
];

// ==========================================
// 9. SEED ENROLLMENTS (With Pre/Post Scores)
// ==========================================
export const SEED_ENROLLMENTS: IEnrollment[] = [
  // Trainee 1 (Pooja Iyer) completed Course 1:
  // Pre-test: 42%, Post-test: 81%, Improvement: +39 percentage points!
  {
    _id: 'enr_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_001',
    status: 'completed',
    progressPercentage: 100,
    completedLessonIds: ['les_1_1_1', 'les_1_1_2', 'les_1_2_1', 'les_1_2_2', 'les_1_3_1', 'les_1_4_1'],
    enrolledAt: '2026-02-01T09:00:00Z',
    preAssessmentScore: 42, // Baseline diagnostic score
    preAssessmentDate: '2026-02-01T09:30:00Z',
    assessmentScore: 81, // Post-test score
    postAssessmentDate: '2026-02-28T16:45:00Z',
    improvementPoints: 39, // +39 points improvement!
    completedAt: '2026-02-28T16:45:00Z',
    lastAccessedAt: '2026-03-01T12:00:00Z',
    assessmentAttemptId: 'att_001',
    certificateId: 'IMD-CC-2026-09284',
  },
  // Trainee 1 in-progress in Course 2 (Satellite)
  {
    _id: 'enr_002',
    courseId: 'course_002',
    courseTitle: 'Satellite Meteorology',
    traineeId: 'usr_trainee_001',
    status: 'in-progress',
    progressPercentage: 50,
    completedLessonIds: ['les_2_1_1'],
    enrolledAt: '2026-03-05T09:30:00Z',
    preAssessmentScore: 46,
    preAssessmentDate: '2026-03-05T10:00:00Z',
    lastAccessedAt: '2026-03-12T11:15:00Z',
  },
  // Trainee 2 (Amitabh) completed Course 1: Pre 50%, Post 82%, Imp +32
  {
    _id: 'enr_003',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_002',
    status: 'completed',
    progressPercentage: 100,
    completedLessonIds: ['les_1_1_1', 'les_1_1_2', 'les_1_2_1', 'les_1_2_2', 'les_1_3_1', 'les_1_4_1'],
    enrolledAt: '2026-02-05T10:00:00Z',
    preAssessmentScore: 50,
    preAssessmentDate: '2026-02-05T10:30:00Z',
    assessmentScore: 82,
    postAssessmentDate: '2026-02-26T15:00:00Z',
    improvementPoints: 32,
    completedAt: '2026-02-26T15:00:00Z',
    lastAccessedAt: '2026-02-27T10:00:00Z',
    certificateId: 'IMD-CC-2026-09285',
  },
  // Trainee 3 (Kavita) completed Course 1: Pre 44%, Post 78%, Imp +34
  {
    _id: 'enr_004',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_003',
    status: 'completed',
    progressPercentage: 100,
    completedLessonIds: ['les_1_1_1', 'les_1_1_2', 'les_1_2_1', 'les_1_2_2', 'les_1_3_1', 'les_1_4_1'],
    enrolledAt: '2026-02-08T09:00:00Z',
    preAssessmentScore: 44,
    preAssessmentDate: '2026-02-08T09:30:00Z',
    assessmentScore: 78,
    postAssessmentDate: '2026-02-27T16:00:00Z',
    improvementPoints: 34,
    completedAt: '2026-02-27T16:00:00Z',
    lastAccessedAt: '2026-02-28T11:00:00Z',
    certificateId: 'IMD-CC-2026-09286',
  },
  // Trainee 4 (Rohan) completed Course 3 (Python): Pre 52%, Post 76%, Imp +24
  {
    _id: 'enr_005',
    courseId: 'course_003',
    courseTitle: 'Python for Meteorological Data Analysis',
    traineeId: 'usr_trainee_004',
    status: 'completed',
    progressPercentage: 100,
    completedLessonIds: ['les_3_1_1'],
    enrolledAt: '2026-02-12T10:00:00Z',
    preAssessmentScore: 52,
    preAssessmentDate: '2026-02-12T10:30:00Z',
    assessmentScore: 76,
    postAssessmentDate: '2026-02-28T12:00:00Z',
    improvementPoints: 24,
    completedAt: '2026-02-28T12:00:00Z',
    lastAccessedAt: '2026-03-01T09:00:00Z',
    certificateId: 'IMD-CC-2026-09287',
  },
];

// ==========================================
// 10. SEED CERTIFICATES (Feature 21)
// ==========================================
export const SEED_CERTIFICATES: ICertificate[] = [
  {
    _id: 'cert_001',
    certificateId: 'CC-2026-000128',
    traineeId: 'usr_trainee_001',
    traineeName: 'Pooja Iyer',
    traineeDepartment: 'Regional Meteorological Centre, Mumbai',
    courseId: 'course_001',
    courseName: 'Weather Forecasting Fundamentals',
    trainerName: 'Dr. Rajesh Sharma',
    issueDate: '2026-02-28T16:50:00Z',
    completionDate: '2026-02-28T16:45:00Z',
    preScorePercentage: 42,
    scorePercentage: 81,
    verificationCode: 'CC-2026-000128',
    verificationUrl: '/verify/CC-2026-000128',
  },
  {
    _id: 'cert_002',
    certificateId: 'CC-2026-000129',
    traineeId: 'usr_trainee_002',
    traineeName: 'Amitabh Mukherjee',
    traineeDepartment: 'Doppler Radar Station, Kolkata',
    courseId: 'course_001',
    courseName: 'Weather Forecasting Fundamentals',
    trainerName: 'Dr. Rajesh Sharma',
    issueDate: '2026-02-26T15:05:00Z',
    completionDate: '2026-02-26T15:00:00Z',
    preScorePercentage: 50,
    scorePercentage: 82,
    verificationCode: 'CC-2026-000129',
    verificationUrl: '/verify/CC-2026-000129',
  },
];

// ==========================================
// 11. SEED PERSONALIZED LEARNING PATH (Feature 4)
// ==========================================
export const SEED_LEARNING_PATHS: ILearningPath[] = [
  {
    _id: 'lp_001',
    userId: 'usr_trainee_001',
    roleTemplateId: 'role_01',
    title: 'Weather Forecasting Learning Path',
    goal: 'Achieve Operational Duty Forecaster Credential for Regional Meteorological Centres',
    targetRole: 'Weather Forecaster',
    progress: 55,
    estimatedDuration: '16 Weeks',
    currentStep: 3,
    nextRecommendedStep: 'Forecasting Fundamentals',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z',
    steps: [
      {
        id: 'lp_step_1',
        stepNumber: 1,
        courseId: 'course_004',
        title: '01 Meteorology Basics',
        description: 'Atmospheric layers, thermodynamic equations, and solar radiation budget.',
        type: 'course',
        duration: '3 Weeks',
        status: 'completed',
        score: 88,
        completedAt: '2026-02-15T12:00:00Z',
      },
      {
        id: 'lp_step_2',
        stepNumber: 2,
        courseId: 'course_004',
        title: '02 Weather Observation',
        description: 'Stevenson screen instrument checks, AWS telemetry, and UTC synoptic hours.',
        type: 'course',
        duration: '3 Weeks',
        status: 'completed',
        score: 82,
        completedAt: '2026-02-25T14:00:00Z',
      },
      {
        id: 'lp_step_3',
        stepNumber: 3,
        courseId: 'course_003',
        title: '03 Meteorological Data Analysis',
        description: 'Working with NetCDF gridded data, Xarray time slices, and Python contouring.',
        type: 'course',
        duration: '3 Weeks',
        status: 'current',
      },
      {
        id: 'lp_step_4',
        stepNumber: 4,
        courseId: 'course_001',
        title: '04 Forecasting Fundamentals',
        description: 'Synoptic chart plotting, trough lines, cyclonic circulation, and warnings.',
        type: 'course',
        duration: '4 Weeks',
        status: 'in-progress',
      },
      {
        id: 'lp_step_5',
        stepNumber: 5,
        courseId: 'course_002',
        title: '05 Advanced Forecasting',
        description: 'Multi-model ensemble consensus and severe convective nowcasting.',
        type: 'course',
        duration: '4 Weeks',
        status: 'locked',
        prerequisiteStepIds: ['lp_step_4'],
      },
      {
        id: 'lp_step_6',
        stepNumber: 6,
        courseId: 'course_001',
        title: '06 Final Assessment & Practical Simulation',
        description: 'Comprehensive operational shift forecasting simulation and oral board review.',
        type: 'assessment',
        duration: '1 Week',
        status: 'locked',
        prerequisiteStepIds: ['lp_step_5'],
      },
    ],
  },
];

// ==========================================
// 12. SEED DEPARTMENT SKILL HEATMAP (Feature 10)
// ==========================================
export const SEED_DEPARTMENT_HEATMAP: IDepartmentSkillCoverage[] = [
  {
    department: 'Synoptic Forecasting Operations',
    totalEmployees: 48,
    competencies: [
      {
        competencyName: 'Forecasting',
        averageScore: 88,
        requiredScore: 85,
        gap: 0,
        employeeCount: 48,
        recommendedCourses: ['Advanced Synoptic Analysis'],
      },
      {
        competencyName: 'Python',
        averageScore: 64,
        requiredScore: 70,
        gap: 6,
        employeeCount: 48,
        recommendedCourses: ['Python for Meteorological Data Analysis'],
      },
      {
        competencyName: 'Satellite',
        averageScore: 91,
        requiredScore: 80,
        gap: 0,
        employeeCount: 48,
        recommendedCourses: ['INSAT High-Resolution Interpretation'],
      },
      {
        competencyName: 'Meteorology',
        averageScore: 86,
        requiredScore: 80,
        gap: 0,
        employeeCount: 48,
        recommendedCourses: [],
      },
      {
        competencyName: 'Radar',
        averageScore: 72,
        requiredScore: 75,
        gap: 3,
        employeeCount: 48,
        recommendedCourses: ['Doppler Radar Echo Analysis'],
      },
    ],
  },
  {
    department: 'Satellite Meteorology Division',
    totalEmployees: 32,
    competencies: [
      {
        competencyName: 'Forecasting',
        averageScore: 72,
        requiredScore: 75,
        gap: 3,
        employeeCount: 32,
        recommendedCourses: ['Weather Forecasting Fundamentals'],
      },
      {
        competencyName: 'Python',
        averageScore: 42,
        requiredScore: 65,
        gap: 23,
        employeeCount: 32,
        recommendedCourses: ['Python for Meteorological Data Analysis'],
      },
      {
        competencyName: 'Satellite',
        averageScore: 85,
        requiredScore: 85,
        gap: 0,
        employeeCount: 32,
        recommendedCourses: ['INSAT-3DS Sounder Radiance Processing'],
      },
      {
        competencyName: 'Meteorology',
        averageScore: 81,
        requiredScore: 80,
        gap: 0,
        employeeCount: 32,
        recommendedCourses: [],
      },
      {
        competencyName: 'Radar',
        averageScore: 60,
        requiredScore: 65,
        gap: 5,
        employeeCount: 32,
        recommendedCourses: ['Doppler Weather Radar Interpretation'],
      },
    ],
  },
  {
    department: 'Radar & Instrumentation Network',
    totalEmployees: 40,
    competencies: [
      {
        competencyName: 'Forecasting',
        averageScore: 68,
        requiredScore: 75,
        gap: 7,
        employeeCount: 40,
        recommendedCourses: ['Weather Forecasting Fundamentals'],
      },
      {
        competencyName: 'Python',
        averageScore: 58,
        requiredScore: 65,
        gap: 7,
        employeeCount: 40,
        recommendedCourses: ['Python for Meteorological Data Analysis'],
      },
      {
        competencyName: 'Satellite',
        averageScore: 70,
        requiredScore: 75,
        gap: 5,
        employeeCount: 40,
        recommendedCourses: ['Satellite Meteorology'],
      },
      {
        competencyName: 'Meteorology',
        averageScore: 84,
        requiredScore: 80,
        gap: 0,
        employeeCount: 40,
        recommendedCourses: [],
      },
      {
        competencyName: 'Radar',
        averageScore: 92,
        requiredScore: 85,
        gap: 0,
        employeeCount: 40,
        recommendedCourses: ['Advanced Dual-Pol Classification'],
      },
    ],
  },
  {
    department: 'Climate Research & Services',
    totalEmployees: 36,
    competencies: [
      {
        competencyName: 'Forecasting',
        averageScore: 75,
        requiredScore: 75,
        gap: 0,
        employeeCount: 36,
        recommendedCourses: [],
      },
      {
        competencyName: 'Python',
        averageScore: 82,
        requiredScore: 75,
        gap: 0,
        employeeCount: 36,
        recommendedCourses: ['Advanced ML for Climate'],
      },
      {
        competencyName: 'Satellite',
        averageScore: 68,
        requiredScore: 70,
        gap: 2,
        employeeCount: 36,
        recommendedCourses: ['Satellite Meteorology'],
      },
      {
        competencyName: 'Meteorology',
        averageScore: 88,
        requiredScore: 80,
        gap: 0,
        employeeCount: 36,
        recommendedCourses: [],
      },
      {
        competencyName: 'Radar',
        averageScore: 65,
        requiredScore: 70,
        gap: 5,
        employeeCount: 36,
        recommendedCourses: ['Doppler Weather Radar Interpretation'],
      },
    ],
  },
];

// ==========================================
// 13. SEED TRAINING EVENTS / CALENDAR (Feature 16)
// ==========================================
export const SEED_TRAINING_EVENTS: ITrainingEvent[] = [
  {
    _id: 'evt_001',
    title: 'Live Workshop: Severe Weather Nowcasting & Doppler Radar Echoes',
    description: 'Interactive live session covering squall lines, bow echoes, and microburst signatures with Dr. Sunita Rao.',
    type: 'live_session',
    date: '2026-03-30',
    time: '11:00 AM - 01:00 PM IST',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    targetRole: 'all',
    locationOrLink: 'IMD Central Webex Session (Hall A)',
  },
  {
    _id: 'evt_002',
    title: 'Pre-Assessment Submission Deadline: Weather Forecasting Fundamentals',
    description: 'Mandatory completion of the 20-minute diagnostic baseline assessment.',
    type: 'assessment_deadline',
    date: '2026-04-02',
    time: '05:00 PM IST',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    targetRole: 'trainee',
    locationOrLink: 'Capacity Connect Assessment Portal',
  },
  {
    _id: 'evt_003',
    title: 'Batch Start: Climate Data Analysis & Extreme Weather Modeling',
    description: 'Kick-off lecture on Generalized Extreme Value (GEV) modeling with Dr. Vikram Verma.',
    type: 'course_start',
    date: '2026-04-05',
    time: '10:00 AM - 12:00 PM IST',
    courseId: 'course_005',
    courseTitle: 'Climate Data Analysis & Extreme Weather Modeling',
    targetRole: 'trainee',
    locationOrLink: 'CRS Lecture Theatre, Pune / Virtual Room 2',
  },
  {
    _id: 'evt_004',
    title: 'Annual Cyclone Preparedness Workshop (Bay of Bengal & Arabian Sea)',
    description: 'High-level operational briefing with Divisional Heads and RMC forecasters.',
    type: 'workshop',
    date: '2026-04-10',
    time: '09:30 AM - 05:30 PM IST',
    targetRole: 'all',
    locationOrLink: 'IMD HQ Auditorium, Mausam Bhavan, New Delhi',
  },
  {
    _id: 'evt_005',
    title: 'Certificate Expiry Alert: Radiosonde Operator Credential',
    description: 'Annual re-certification required for upper-air radiosonde launch safety procedures.',
    type: 'cert_expiry',
    date: '2026-04-20',
    time: '11:59 PM IST',
    targetRole: 'trainee',
    userId: 'usr_trainee_001',
    locationOrLink: 'Training Renewal Desk',
  },
];

// ==========================================
// 14. SEED TRAINER LIBRARY (Feature 15)
// ==========================================
export const SEED_TRAINER_LIBRARY: ITrainerLibraryResource[] = [
  {
    id: 'res_lib_001',
    trainerId: 'usr_trainer_001',
    folder: 'Weather Forecasting',
    title: 'Lecture 01 - Atmospheric Dynamics & Synoptic Systems.mp4',
    type: 'video',
    fileName: 'Lecture 01 - Synoptic Systems.mp4',
    fileSize: '420 MB',
    fileUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    uploadedAt: '2026-01-18T10:00:00Z',
    usedInCourses: ['course_001'],
  },
  {
    id: 'res_lib_002',
    trainerId: 'usr_trainer_001',
    folder: 'Weather Forecasting',
    title: 'Forecasting Notes & Tephigram Plotting Manual.pdf',
    type: 'pdf',
    fileName: 'Forecasting Notes.pdf',
    fileSize: '4.8 MB',
    fileUrl: '/docs/forecasting_notes.pdf',
    uploadedAt: '2026-01-20T12:00:00Z',
    usedInCourses: ['course_001'],
  },
  {
    id: 'res_lib_003',
    trainerId: 'usr_trainer_001',
    folder: 'Weather Forecasting',
    title: 'Standard Synoptic Analysis Protocols & Warning Criteria.pptx',
    type: 'presentation',
    fileName: 'Forecasting.pptx',
    fileSize: '12.5 MB',
    fileUrl: '/docs/forecasting_protocols.pptx',
    uploadedAt: '2026-01-22T14:00:00Z',
    usedInCourses: ['course_001'],
  },
  {
    id: 'res_lib_004',
    trainerId: 'usr_trainer_002',
    folder: 'Satellite Meteorology',
    title: 'Satellite Basics & INSAT-3DR Radiance Windows.pdf',
    type: 'pdf',
    fileName: 'Satellite Basics.pdf',
    fileSize: '6.2 MB',
    fileUrl: '/docs/satellite_basics.pdf',
    uploadedAt: '2026-01-28T11:00:00Z',
    usedInCourses: ['course_002'],
  },
  {
    id: 'res_lib_005',
    trainerId: 'usr_trainer_002',
    folder: 'Satellite Meteorology',
    title: 'Dvorak Cyclone Pattern Interpretation & RGB Compositing.pptx',
    type: 'presentation',
    fileName: 'Image Interpretation.pptx',
    fileSize: '18.4 MB',
    fileUrl: '/docs/image_interpretation.pptx',
    uploadedAt: '2026-02-02T16:00:00Z',
    usedInCourses: ['course_002'],
  },
];

// ==========================================
// 15. SEED NOTIFICATIONS (Feature 17)
// ==========================================
export const SEED_NOTIFICATIONS: INotification[] = [
  {
    _id: 'notif_001',
    userId: 'usr_trainee_001',
    title: 'Assessment Deadline Approaching',
    message: 'Assessment deadline tomorrow for Weather Forecasting Fundamentals module.',
    read: false,
    type: 'deadline',
    link: '/trainee/assessments',
    createdAt: '2026-03-27T08:00:00Z',
  },
  {
    _id: 'notif_002',
    userId: 'usr_trainee_001',
    title: 'Role Competency Gap Detected',
    message: 'Your Forecasting competency (45%) is below the selected role requirement (80%).',
    read: false,
    type: 'competency_gap',
    link: '/trainee/competencies',
    createdAt: '2026-03-26T10:30:00Z',
  },
  {
    _id: 'notif_003',
    userId: 'usr_trainee_001',
    title: 'Smart Course Recommendation',
    message: 'A new course matching your competency gaps is available: Weather Forecasting Fundamentals.',
    read: true,
    type: 'recommendation',
    link: '/courses/course_001',
    createdAt: '2026-03-25T14:00:00Z',
  },
  {
    _id: 'notif_004',
    userId: 'usr_trainee_001',
    title: 'Course Milestone Reached',
    message: 'You have completed 80% of your current course: Weather Forecasting Fundamentals.',
    read: true,
    type: 'progress',
    link: '/trainee/courses',
    createdAt: '2026-03-24T16:00:00Z',
  },
  {
    _id: 'notif_005',
    userId: 'usr_trainee_001',
    title: 'Certificate Renewal Notice',
    message: 'Your Radiosonde Upper-Air Sounding certification expires in 30 days.',
    read: true,
    type: 'cert_expiry',
    link: '/trainee/certificates',
    createdAt: '2026-03-20T11:00:00Z',
  },
];

// ==========================================
// 16. SEED ANNOUNCEMENTS
// ==========================================
export const SEED_ANNOUNCEMENTS: IAnnouncement[] = [
  {
    _id: 'ann_001',
    title: 'National Pre-Monsoon Capacity Building Workshop 2026',
    content:
      'The Director General of Meteorology announces the mandatory pre-monsoon capacity building drive. All Scientific Assistants and Operational Forecasters at coastal and river basin stations must complete the Satellite Meteorology and Doppler Radar Refresher courses before April 15, 2026.',
    type: 'urgent',
    targetRole: 'all',
    author: 'Directorate General, IMD HQ New Delhi',
    priority: 'high',
    createdAt: '2026-03-01T09:00:00Z',
  },
  {
    _id: 'ann_002',
    title: 'New Competency Mapping Framework Deployed',
    content:
      'Capacity Connect portal now automatically maps competency scores across 10 core meteorological domains and highlights targeted skill gaps for personnel upskilling and career progression.',
    type: 'achievement',
    targetRole: 'all',
    author: 'IMD Central Training Division, Pune',
    priority: 'normal',
    createdAt: '2026-02-20T11:30:00Z',
  },
  {
    _id: 'ann_003',
    title: 'Trainer Competency Matching System Operational',
    content:
      'Divisional heads can now calculate transparent competency matches when assigning certified trainers to regional training institutes across New Delhi, Pune, Kolkata, Chennai, Guwahati, and Mumbai.',
    type: 'general',
    targetRole: 'trainer',
    author: 'Capacity Assessment Directorate',
    priority: 'normal',
    createdAt: '2026-02-10T14:00:00Z',
  },
];

// ==========================================
// 17. SEED FEEDBACKS (Feature 24)
// ==========================================
export const SEED_FEEDBACKS: IFeedback[] = [
  {
    _id: 'fb_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_001',
    traineeName: 'Pooja Iyer',
    trainerId: 'usr_trainer_001',
    rating: 5,
    trainerRating: 5,
    comments:
      'Outstanding modules! The explanation of thermodynamic tephigram diagrams, CAPE analysis, and severe weather warning criteria directly helped my shift duties at RMC Mumbai.',
    createdAt: '2026-03-01T17:00:00Z',
  },
  {
    _id: 'fb_002',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_002',
    traineeName: 'Amitabh Mukherjee',
    trainerId: 'usr_trainer_001',
    rating: 4.8,
    trainerRating: 5,
    comments:
      'The synoptic chart exercises are highly practical. Would appreciate more exercises on squall line nowcasting in the Bay of Bengal.',
    createdAt: '2026-02-27T11:00:00Z',
  },
];
