import {
  IUser,
  ITraineeProfile,
  ITrainerProfile,
  ICourse,
  IAssessment,
  IEnrollment,
  ICertificate,
  ICompetency,
  ITraineeCompetency,
  ISkillGap,
  IAnnouncement,
  IFeedback,
} from './types';

export const SEED_PASSWORD_HASH = '$2a$10$7ZzT2r/rIomk37V/549Q1.8wKz.hV698F53iCqYl4J2nZzUsmzG5a'; // Hash of 'Password123!'
export const DEMO_PASSWORD = 'Password123!';

export const SEED_USERS: IUser[] = [
  {
    _id: 'usr_admin_001',
    name: 'Dr. M. Mohapatra (Admin)',
    email: 'admin@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'admin',
    status: 'approved',
    department: 'Directorate General, IMD HQ',
    designation: 'Director General & Capacity Administrator',
    phone: '+91 11 2461 1068',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    _id: 'usr_trainer_001',
    name: 'Dr. Rajesh Sharma',
    email: 'trainer@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Numerical Weather Prediction Division',
    designation: 'Senior Meteorologist & Chief Trainer',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    _id: 'usr_trainer_002',
    name: 'Dr. Ananya Sen',
    email: 'ananya.sen@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Satellite Meteorology Division',
    designation: 'Principal Satellite Meteorologist',
    phone: '+91 98111 22334',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    _id: 'usr_trainer_003',
    name: 'Dr. Vikram Verma',
    email: 'vikram.verma@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'approved',
    department: 'Climate Research and Services, Pune',
    designation: 'Lead NWP Modeling Specialist',
    phone: '+91 97234 56789',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    createdAt: '2026-01-18T14:00:00Z',
  },
  {
    _id: 'usr_trainee_001',
    name: 'Pooja Iyer',
    email: 'trainee@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'approved',
    department: 'Regional Meteorological Centre, Mumbai',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94444 12345',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    createdAt: '2026-02-01T08:30:00Z',
  },
  {
    _id: 'usr_trainee_002',
    name: 'Amitabh Mukherjee',
    email: 'amitabh.m@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainee',
    status: 'pending',
    department: 'Doppler Radar Station, Kolkata',
    designation: 'Meteorologist-A',
    phone: '+91 98300 45678',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    createdAt: '2026-03-01T10:15:00Z',
  },
  {
    _id: 'usr_trainer_pending',
    name: 'Dr. K. Srinivas',
    email: 'k.srinivas@capacityconnect.demo',
    passwordHash: SEED_PASSWORD_HASH,
    role: 'trainer',
    status: 'pending',
    department: 'Cyclone Warning Centre, Visakhapatnam',
    designation: 'Senior Scientist (Tropical Cyclones)',
    phone: '+91 98480 99887',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    createdAt: '2026-03-05T12:00:00Z',
  },
];

export const SEED_TRAINEE_PROFILES: ITraineeProfile[] = [
  {
    _id: 'prof_trainee_001',
    userId: 'usr_trainee_001',
    department: 'Regional Meteorological Centre, Mumbai',
    designation: 'Scientific Assistant Grade-I',
    phone: '+91 94444 12345',
    bio: 'Dedicated atmospheric sciences professional with 3+ years experience supporting coastal synoptic observations, radar tracking, and AWS calibration for coastal Maharashtra.',
    education: [
      {
        degree: 'Master of Science (M.Sc.)',
        institution: 'Pune University (SPPU) - Department of Atmospheric and Space Sciences',
        qualification: 'Meteorology & Atmospheric Physics',
        year: '2022',
      },
      {
        degree: 'Bachelor of Science (B.Sc.)',
        institution: 'St. Xaviers College, Mumbai',
        qualification: 'Physics and Mathematics (Honors)',
        year: '2020',
      },
    ],
    experience: [
      {
        organization: 'India Meteorological Department (IMD)',
        position: 'Scientific Assistant Grade-I',
        years: 3,
      },
      {
        organization: 'Indian Institute of Tropical Meteorology (IITM)',
        position: 'Project Research Intern',
        years: 1,
      },
    ],
    skills: [
      'Meteorological Observations',
      'Python (Pandas, MetPy)',
      'Synoptic Chart Analysis',
      'Radar Data Plotting',
      'AWS Maintenance',
      'Data Quality Control',
    ],
    interests: [
      'Monsoon Depression Dynamics',
      'Satellite Infrared Band Interpretation',
      'Nowcasting Severe Thunderstorms',
      'AI in Tropical Weather Prediction',
    ],
    completedCertificatesCount: 1,
    updatedAt: '2026-03-10T14:20:00Z',
  },
];

export const SEED_TRAINER_PROFILES: ITrainerProfile[] = [
  {
    _id: 'prof_trainer_001',
    userId: 'usr_trainer_001',
    name: 'Dr. Rajesh Sharma',
    department: 'Numerical Weather Prediction Division, New Delhi',
    designation: 'Senior Meteorologist & Chief Trainer',
    bio: 'Over 14 years of research and operational weather forecasting leadership at IMD HQ. Specialized in synoptic analysis, NWP models (WRF, GFS), and training national forecasters.',
    experienceYears: 14,
    specializations: ['Synoptic Meteorology', 'Weather Forecasting', 'NWP Guidance Interpretation', 'Severe Weather Warning'],
    competencies: [
      { name: 'Meteorology', domain: 'Core Meteorological Science', level: 'Advanced', score: 96 },
      { name: 'Weather Forecasting', domain: 'Synoptic Operations', level: 'Advanced', score: 94 },
      { name: 'Data Analysis', domain: 'Computational Meteorology', level: 'Advanced', score: 88 },
      { name: 'Numerical Weather Prediction', domain: 'Model Dynamics', level: 'Advanced', score: 92 },
      { name: 'Climate Science', domain: 'Climatology', level: 'Intermediate', score: 80 },
    ],
    rating: 4.9,
    totalCourses: 2,
    totalStudentsTaught: 142,
  },
  {
    _id: 'prof_trainer_002',
    userId: 'usr_trainer_002',
    name: 'Dr. Ananya Sen',
    department: 'Satellite Meteorology Division, New Delhi',
    designation: 'Principal Satellite Meteorologist',
    bio: 'Lead specialist in INSAT-3D, 3DR, and 3DS multispectral imagery, sounder retrievals, and rapid scan nowcasting for convective systems over the Indian subcontinent.',
    experienceYears: 11,
    specializations: ['Satellite Meteorology', 'INSAT Payloads', 'Cloud Motion Vectors', 'Remote Sensing'],
    competencies: [
      { name: 'Satellite Meteorology', domain: 'Earth Observation', level: 'Advanced', score: 98 },
      { name: 'Meteorology', domain: 'Core Meteorological Science', level: 'Advanced', score: 90 },
      { name: 'Data Analysis', domain: 'Computational Meteorology', level: 'Advanced', score: 85 },
      { name: 'Python', domain: 'Scientific Programming', level: 'Intermediate', score: 75 },
    ],
    rating: 4.8,
    totalCourses: 1,
    totalStudentsTaught: 98,
  },
  {
    _id: 'prof_trainer_003',
    userId: 'usr_trainer_003',
    name: 'Dr. Vikram Verma',
    department: 'Climate Research and Services, Pune',
    designation: 'Lead NWP Modeling Specialist',
    bio: 'Expert computational atmospheric physicist focusing on high-resolution convective scale modeling, ensemble forecasting, Python workflow automation, and NetCDF processing.',
    experienceYears: 9,
    specializations: ['Python for Meteorology', 'NetCDF / GRIB2 Processing', 'Numerical Weather Prediction', 'Data Analysis'],
    competencies: [
      { name: 'Python', domain: 'Scientific Programming', level: 'Advanced', score: 95 },
      { name: 'Data Analysis', domain: 'Computational Meteorology', level: 'Advanced', score: 92 },
      { name: 'Numerical Weather Prediction', domain: 'Model Dynamics', level: 'Advanced', score: 89 },
      { name: 'Meteorology', domain: 'Core Meteorological Science', level: 'Intermediate', score: 82 },
    ],
    rating: 4.95,
    totalCourses: 1,
    totalStudentsTaught: 120,
  },
];

export const SEED_COMPETENCIES: ICompetency[] = [
  {
    _id: 'comp_01',
    name: 'Meteorology',
    domain: 'Core Meteorological Science',
    description: 'Fundamental principles of atmospheric thermodynamics, radiation, dynamics, hydrostatic balance, and cloud microphysics.',
    category: 'Core Science',
    icon: 'CloudSun',
    targetBenchmark: 80,
  },
  {
    _id: 'comp_02',
    name: 'Weather Forecasting',
    domain: 'Synoptic Operations',
    description: 'Surface and upper-air synoptic chart interpretation, frontogenesis, cyclogenesis, nowcasting severe storms, and public weather bulletin preparation.',
    category: 'Operational Skills',
    icon: 'Compass',
    targetBenchmark: 75,
  },
  {
    _id: 'comp_03',
    name: 'Data Analysis',
    domain: 'Computational Meteorology',
    description: 'Statistical analysis of meteorological time series, trend analysis, extreme value analysis, anomaly detection, and data assimilation concepts.',
    category: 'Analytics',
    icon: 'BarChart3',
    targetBenchmark: 70,
  },
  {
    _id: 'comp_04',
    name: 'Python',
    domain: 'Scientific Programming',
    description: 'Python programming using NumPy, Pandas, Xarray, MetPy, and Cartopy for atmospheric datasets, automated alert generation, and GIS contouring.',
    category: 'Programming',
    icon: 'Code',
    targetBenchmark: 75,
  },
  {
    _id: 'comp_05',
    name: 'Satellite Meteorology',
    domain: 'Earth Observation',
    description: 'Understanding geostationary & polar-orbiting satellites, INSAT-3DR visible, infrared, and water vapor channels, RGB composites, and wind vector tracking.',
    category: 'Remote Sensing',
    icon: 'Radio',
    targetBenchmark: 80,
  },
  {
    _id: 'comp_06',
    name: 'Climate Science',
    domain: 'Climatology',
    description: 'Long-range climate variability, ENSO, Indian Ocean Dipole (IOD), Madden-Julian Oscillation (MJO), climate normals, and IPCC assessment downscaling.',
    category: 'Climate & Research',
    icon: 'Globe',
    targetBenchmark: 70,
  },
  {
    _id: 'comp_07',
    name: 'Numerical Weather Prediction',
    domain: 'Model Dynamics',
    description: 'Governing primitive equations, grid systems, boundary conditions, parameterization schemes, and multi-model ensemble consensus forecasting.',
    category: 'Modeling',
    icon: 'Cpu',
    targetBenchmark: 75,
  },
];

export const SEED_TRAINEE_COMPETENCIES: ITraineeCompetency[] = [
  {
    _id: 'tc_01',
    traineeId: 'usr_trainee_001',
    competencyName: 'Meteorology',
    domain: 'Core Meteorological Science',
    level: 'Advanced',
    score: 85,
    lastUpdated: '2026-02-20T10:00:00Z',
  },
  {
    _id: 'tc_02',
    traineeId: 'usr_trainee_001',
    competencyName: 'Python',
    domain: 'Scientific Programming',
    level: 'Intermediate',
    score: 70,
    lastUpdated: '2026-03-01T15:30:00Z',
  },
  {
    _id: 'tc_03',
    traineeId: 'usr_trainee_001',
    competencyName: 'Data Analysis',
    domain: 'Computational Meteorology',
    level: 'Intermediate',
    score: 55,
    lastUpdated: '2026-02-15T09:15:00Z',
  },
  {
    _id: 'tc_04',
    traineeId: 'usr_trainee_001',
    competencyName: 'Weather Forecasting',
    domain: 'Synoptic Operations',
    level: 'Beginner',
    score: 45,
    lastUpdated: '2026-01-25T11:00:00Z',
  },
  {
    _id: 'tc_05',
    traineeId: 'usr_trainee_001',
    competencyName: 'Satellite Meteorology',
    domain: 'Earth Observation',
    level: 'Beginner',
    score: 40,
    lastUpdated: '2026-01-10T12:00:00Z',
  },
  {
    _id: 'tc_06',
    traineeId: 'usr_trainee_001',
    competencyName: 'Climate Science',
    domain: 'Climatology',
    level: 'Intermediate',
    score: 60,
    lastUpdated: '2026-02-05T14:00:00Z',
  },
  {
    _id: 'tc_07',
    traineeId: 'usr_trainee_001',
    competencyName: 'Numerical Weather Prediction',
    domain: 'Model Dynamics',
    level: 'Beginner',
    score: 35,
    lastUpdated: '2026-01-15T08:45:00Z',
  },
];

export const SEED_SKILL_GAPS: ISkillGap[] = [
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Weather Forecasting',
    currentScore: 45,
    requiredScore: 75,
    gap: 30,
    status: 'Critical',
    recommendedCourseIds: ['course_001'],
  },
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Satellite Meteorology',
    currentScore: 40,
    requiredScore: 80,
    gap: 40,
    status: 'Critical',
    recommendedCourseIds: ['course_002'],
  },
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Data Analysis',
    currentScore: 55,
    requiredScore: 70,
    gap: 15,
    status: 'Moderate',
    recommendedCourseIds: ['course_003'],
  },
  {
    traineeId: 'usr_trainee_001',
    competencyName: 'Python',
    currentScore: 70,
    requiredScore: 75,
    gap: 5,
    status: 'Satisfied',
    recommendedCourseIds: ['course_003'],
  },
];

export const SEED_COURSES: ICourse[] = [
  {
    _id: 'course_001',
    title: 'Weather Forecasting Fundamentals',
    slug: 'weather-forecasting-fundamentals',
    description:
      'A foundational certification course covering atmospheric dynamics, synoptic chart analysis, observation station procedures, and basic weather forecasting protocols used across IMD forecasting centers.',
    category: 'Synoptic Meteorology & Forecasting',
    difficulty: 'Beginner',
    duration: '4 Weeks (20 Hours)',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    trainerRole: 'Senior Meteorologist & Chief Trainer',
    thumbnail: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Synoptic', 'Forecast', 'Observation', 'Atmospheric Physics'],
    enrolledCount: 84,
    rating: 4.9,
    ratingCount: 38,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Weather Forecasting',
    competencyGainPercentage: 30,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-15T12:00:00Z',
    assessmentId: 'assess_001',
    modules: [
      {
        id: 'mod_1_1',
        title: 'Module 1: Introduction to Meteorology',
        description: 'Atmospheric layers, solar radiation budget, temperature profiles, and barometric pressure laws.',
        order: 1,
        lessons: [
          {
            id: 'les_1_1_1',
            title: '1.1 Composition and Structure of the Atmosphere',
            description: 'Exploration of troposphere, stratosphere, mesosphere, and thermosphere with lapse rate calculations.',
            order: 1,
            duration: '25 mins',
            type: 'article',
            contentBody: `### Atmospheric Layers & Vertical Thermal Profiles\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nEarth's atmosphere is divided into distinct thermal strata based on temperature lapse rate gradients:\n\n1. **Troposphere**: Extends from ground to ~16-18 km in tropical regions (such as India) and ~8 km at poles. Characterized by average environmental lapse rate of 6.5°C/km. Nearly all convective weather, clouds, cyclones, and monsoon troughs occur within this sphere.\n2. **Tropopause**: Inversion boundary acting as a lid to vertical convection, crucial for identifying jet stream cores.\n3. **Stratosphere**: Extends to ~50 km where ozone absorption of UV generates positive thermal inversion.\n\n#### Key Formula:\nHydrostatic Equation: $dP = -\\rho g dz = -\\frac{P g}{R_d T} dz$\nIntegrating gives the hypsometric equation for geopotential thickness between pressure surfaces.`,
            resources: [
              {
                id: 'res_1_1',
                title: 'Atmospheric Layers Reference Guide.pdf',
                type: 'pdf',
                fileUrl: '/docs/atmospheric_layers_reference.pdf',
                fileSize: '1.4 MB',
              },
            ],
          },
          {
            id: 'les_1_1_2',
            title: '1.2 Atmospheric Pressure & Wind Dynamics',
            description: 'Pressure gradient force, Coriolis acceleration, geostrophic and gradient wind approximations.',
            order: 2,
            duration: '35 mins',
            type: 'video',
            contentUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // safe embed
            contentBody: `### Forces Governing Atmospheric Motion\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nIn meteorological coordinate systems, horizontal air parcels are governed by:\n- **Pressure Gradient Force (PGF)**: Directs from high to low pressure perpendicular to isobars.\n- **Coriolis Force ($f = 2\\Omega \\sin\\phi$)**: Deflects winds to the right in Northern Hemisphere and left in Southern Hemisphere.\n- **Friction Force**: Significant in planetary boundary layer (PBL) below 1 km, causing cross-isobaric inward flow into low-pressure centers (convergence) and outward flow from highs (divergence).`,
          },
        ],
      },
      {
        id: 'mod_1_2',
        title: 'Module 2: Weather Observation Systems',
        description: 'Surface meteorological instruments, AWS (Automatic Weather Stations), radiosonde soundings, and Doppler radars.',
        order: 2,
        lessons: [
          {
            id: 'les_1_2_1',
            title: '2.1 Surface Instruments & Stevenson Screen Protocols',
            description: 'Standard exposure, dry/wet bulb thermometers, barometers, anemometers, and rain gauges.',
            order: 1,
            duration: '30 mins',
            type: 'presentation',
            contentBody: `### Standard IMD Surface Meteorological Observation Protocol\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n#### Routine Synoptic Hours:\nObservations are recorded at UTC standard synoptic intervals (00, 03, 06, 09, 12, 15, 18, 21 UTC) corresponding to 0530, 0830, 1130, 1430, 1730, 2030, 2330, and 0230 IST.\n\n#### Instrument Checks:\n- **Stevenson Screen**: Double-louvered white screen mounted at 1.25 m above natural turf surface.\n- **Dry & Wet Bulb**: Psychrometric formula yields dew point temperature and relative humidity.\n- **Barometer Reduction**: Reducing station level pressure (QFE) to Mean Sea Level (MSL / QFF) via hypsometric reduction tables.`,
          },
          {
            id: 'les_1_2_2',
            title: '2.2 Automatic Weather Station (AWS) & Radiosonde Tephigrams',
            description: 'Upper air thermodynamic diagrams (Tephigram) plotting and instability index evaluation (CAPE, CIN).',
            order: 2,
            duration: '40 mins',
            type: 'article',
            contentBody: `### Tephigram Analysis & Convective Instability\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nThe Tephigram ($T-\\phi$ gram, temperature and entropy) is IMD's standard thermodynamic chart.\n\n#### Severe Weather Parameters:\n- **LCL (Lifting Condensation Level)**: Base of convective clouds.\n- **LFC (Level of Free Convection)**: Point where parcel temperature exceeds ambient environment.\n- **CAPE (Convective Available Potential Energy)**: $> 1500$ J/kg indicates moderate to severe thunderstorm potential.\n- **CIN (Convective Inhibition)**: Barrier energy required to be overcome by diurnal solar heating or low-level convergence.`,
          },
        ],
      },
      {
        id: 'mod_1_3',
        title: 'Module 3: Forecasting Basics',
        description: 'Synoptic charts, trough lines, cyclonic circulations, jet streams, and monsoon depressions.',
        order: 3,
        lessons: [
          {
            id: 'les_1_3_1',
            title: '3.1 Synoptic Chart Plotting & Frontal/Tropical Systems',
            description: 'Station model plots, isobaric drawing at 2 hPa intervals, and streamline/isotach analysis.',
            order: 1,
            duration: '45 mins',
            type: 'article',
            contentBody: `### Synoptic Weather Chart Analysis Procedures\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nIn tropical meteorology, pressure gradients are typically weak compared to mid-latitudes, making streamline analysis and moisture convergence charts essential.\n\n1. Plot surface reports using standard WMO station models: wind barb, cloud amount in oktas, present weather symbols ($ww$), barometric tendency.\n2. Trace the Monsoon Trough line extending from Ganganagar to Kolkata and the Head Bay of Bengal.\n3. Identify Embedded Cyclonic Circulations ($cycir$) at 0.9 km, 1.5 km, 3.1 km, and 5.8 km a.s.l. levels.`,
          },
        ],
      },
      {
        id: 'mod_1_4',
        title: 'Module 4: Weather Data Interpretation',
        description: 'Synthesizing radar reflectivity, satellite infrared bands, and NWP model guidance into actionable bulletins.',
        order: 4,
        lessons: [
          {
            id: 'les_1_4_1',
            title: '4.1 Integrating Radar, Satellite & NWP Guidance',
            description: 'Step-by-step methodology for severe weather warnings and public impact-based forecasts.',
            order: 1,
            duration: '35 mins',
            type: 'article',
            contentBody: `### Integrated Weather Forecasting Protocol\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nForecasters cross-examine:\n- **Satellite IR/WV loops**: Cloud top brightness temperature ($-60^\\circ$C signifies deep convection).\n- **Doppler Weather Radar (DWR)**: MAX(Z), Plan Position Indicator (PPI), Velocity Azimuth Display (VAD).\n- **Ensemble NWP Outputs**: GFS-T1534, NCUM, and WRF 3km hourly meteograms.`,
          },
        ],
      },
    ],
  },
  {
    _id: 'course_002',
    title: 'Satellite Meteorology',
    slug: 'satellite-meteorology',
    description:
      'Comprehensive study of meteorological satellites with specialized focus on INSAT-3D, 3DR, and 3DS payloads, radiance channels, RGB composite generation, and cyclogenesis monitoring.',
    category: 'Remote Sensing & Earth Observation',
    difficulty: 'Intermediate',
    duration: '5 Weeks (25 Hours)',
    trainerId: 'usr_trainer_002',
    trainerName: 'Dr. Ananya Sen',
    trainerRole: 'Principal Satellite Meteorologist',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Satellite', 'INSAT', 'Remote Sensing', 'Infrared', 'Cyclone'],
    enrolledCount: 62,
    rating: 4.85,
    ratingCount: 29,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Satellite Meteorology',
    competencyGainPercentage: 35,
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-02-28T14:00:00Z',
    assessmentId: 'assess_002',
    modules: [
      {
        id: 'mod_2_1',
        title: 'Module 1: Introduction to Weather Satellites',
        description: 'Orbits (Geostationary vs Polar Sun-Synchronous), Keplerian elements, resolution, and sensor payloads.',
        order: 1,
        lessons: [
          {
            id: 'les_2_1_1',
            title: '1.1 Geostationary vs Polar Orbiting Satellites',
            description: 'INSAT series stationed at 74°E and 82°E vs NOAA/MetOp polar platforms.',
            order: 1,
            duration: '30 mins',
            type: 'article',
            contentBody: `### Orbital Mechanics in Meteorological Satellite Systems\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n- **Geostationary Orbit (GEO)**: ~35,786 km altitude directly above the equator. Orbit period matches Earth's rotation (23h 56m 4s). Fixed sub-satellite point provides continuous hemispheric disc viewing at 15-minute or rapid-scan 4-minute intervals.\n- **Low Earth Sun-Synchronous Orbit (LEO)**: ~800 km altitude, inclined at ~98°. Passes over points at approximately the same local solar time, providing high spatial resolution soundings and microwave scatterometer ocean surface winds.`,
          },
        ],
      },
      {
        id: 'mod_2_2',
        title: 'Module 2: Satellite Imagery & Channels',
        description: 'Visible, Thermal Infrared (TIR1, TIR2), Middle Infrared (MIR), and Water Vapor (WV) channel physics.',
        order: 2,
        lessons: [
          {
            id: 'les_2_2_1',
            title: '2.1 Understanding Radiance Channels & Planck Function',
            description: 'Atmospheric windows and absorption bands of H2O, CO2, and O3.',
            order: 1,
            duration: '40 mins',
            type: 'article',
            contentBody: `### Sensor Spectral Bands on INSAT-3DR\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n1. **Visible (0.55 - 0.75 $\\mu$m)**: 1 km resolution. Albedo measurement of clouds and land surfaces during daylight.\n2. **Thermal Infrared 1 (10.3 - 11.3 $\\mu$m)**: 4 km resolution. Measures cloud-top and ground brightness temperatures 24/7.\n3. **Water Vapor (6.5 - 7.1 $\\mu$m)**: 4 km resolution. Upper-tropospheric moisture transport, jet stream isotachs, and dry intrusion boundaries.`,
          },
        ],
      },
      {
        id: 'mod_2_3',
        title: 'Module 3: Image Interpretation & RGB Composites',
        description: 'Interpreting cellular convection, squall lines, dust storms, fog vs low stratus, and Dvorak cyclone technique.',
        order: 3,
        lessons: [
          {
            id: 'les_2_3_1',
            title: '3.1 Dvorak Tropical Cyclone Intensity Analysis',
            description: 'T-number classification, Curved Band Pattern, Shear Pattern, and Central Dense Overcast (CDO).',
            order: 1,
            duration: '50 mins',
            type: 'presentation',
            contentBody: `### Dvorak Tropical Cyclone Classification Technique\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nThe Dvorak technique relates subjective visual/IR cloud pattern signatures to central pressure ($P_c$) and maximum sustained surface wind speeds ($V_{max}$).\n\n- **T1.0 - T2.0**: Tropical depression stage ($< 33$ knots).\n- **T2.5 - T3.5**: Cyclonic Storm to Severe Cyclonic Storm (34 - 63 knots).\n- **T4.0 - T6.5**: Very Severe to Extremely Severe Cyclonic Storms with embedded warm eye.\n- **T7.0 - T8.0**: Super Cyclonic Storms ($> 120$ knots).`,
          },
        ],
      },
      {
        id: 'mod_2_4',
        title: 'Module 4: Applications in Weather Monitoring',
        description: 'Precipitation estimation (Hydro-Estimator), fog mapping in Indo-Gangetic plains, and forest fire hot spots.',
        order: 4,
        lessons: [
          {
            id: 'les_2_4_1',
            title: '4.1 Winter Fog Detection & Summer Convective Nowcasting',
            description: 'Dual-channel TIR difference ($10.8\\mu m - 3.9\\mu m$) for nighttime radiation fog tracking.',
            order: 1,
            duration: '35 mins',
            type: 'article',
            contentBody: `### Nighttime Fog & Stratus Detection via Brightness Temperature Differences\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nDuring North Indian winter months (Dec-Jan), dense radiation fog severely impacts aviation and rail networks.\nBy subtracting MIR ($3.9\\mu m$) from TIR1 ($10.8\\mu m$), water droplet clouds display positive brightness differences due to droplet emissivity divergence, enabling early fog alerts.`,
          },
        ],
      },
    ],
  },
  {
    _id: 'course_003',
    title: 'Python for Meteorological Data Analysis',
    slug: 'python-for-meteorological-data-analysis',
    description:
      'Hands-on computational training in Python for weather and climate scientists. Master NumPy, Xarray, NetCDF, GRIB2, MetPy thermodynamic plots, and automated geospatial map rendering.',
    category: 'Computational Meteorology & GIS',
    difficulty: 'Intermediate',
    duration: '4 Weeks (20 Hours)',
    trainerId: 'usr_trainer_003',
    trainerName: 'Dr. Vikram Verma',
    trainerRole: 'Lead NWP Modeling Specialist',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop',
    status: 'published',
    tags: ['Python', 'NetCDF', 'Xarray', 'MetPy', 'Cartopy', 'Data Science'],
    enrolledCount: 110,
    rating: 4.95,
    ratingCount: 45,
    disclaimer: 'Prototype Demo Content — Not Official IMD Material.',
    competencyDomain: 'Python',
    competencyGainPercentage: 25,
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    assessmentId: 'assess_003',
    modules: [
      {
        id: 'mod_3_1',
        title: 'Module 1: Python Fundamentals for Atmospheric Sciences',
        description: 'Python environment setup, Conda, Jupyter, array broadcasting, and vectorized operations.',
        order: 1,
        lessons: [
          {
            id: 'les_3_1_1',
            title: '1.1 Scientific Python Stack & Array Operations',
            description: 'NumPy dimensional slicing, NaN mask handling, and unit conversions.',
            order: 1,
            duration: '25 mins',
            type: 'article',
            contentBody: `### NumPy in Meteorological Calculations\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nHandling 4D atmospheric datasets $(time, level, latitude, longitude)$ requires efficient array broadcasting:\n\n\`\`\`python\nimport numpy as np\n\n# Convert Celsius to Kelvin\ntemp_c = np.array([28.4, 30.1, 25.6, 22.0])\ntemp_k = temp_c + 273.15\n\n# Mask missing AWS precipitation records (-999.0)\nprecip = np.array([12.5, -999.0, 45.0, 0.0, -999.0])\nclean_precip = np.where(precip == -999.0, np.nan, precip)\nprint("Mean Daily Rainfall:", np.nanmean(clean_precip), "mm")\n\`\`\``,
          },
        ],
      },
      {
        id: 'mod_3_2',
        title: 'Module 2: Working with Weather Data (NetCDF & GRIB2)',
        description: 'Opening ERA5 reanalysis and IMD gridded daily rainfall data using Xarray and cfgrib.',
        order: 2,
        lessons: [
          {
            id: 'les_3_2_1',
            title: '2.1 Reading Gridded Datasets with Xarray',
            description: 'Selecting coordinate slices, calculating seasonal climatology, and spatial bounding boxes.',
            order: 1,
            duration: '35 mins',
            type: 'article',
            contentBody: `### Xarray Multi-dimensional Gridded Analysis\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n\`\`\`python\nimport xarray as xr\n\n# Open IMD High-Resolution Gridded Daily Rainfall (0.25 x 0.25 degree)\nds = xr.open_dataset('imd_rainfall_2025.nc')\n\n# Slice across peninsular India (8N to 20N, 72E to 85E)\npeninsula_rain = ds['rainfall'].sel(lat=slice(8, 20), lon=slice(72, 85))\nmonsoon_accum = peninsula_rain.sel(time=slice('2025-06-01', '2025-09-30')).sum(dim='time')\n\`\`\``,
          },
        ],
      },
      {
        id: 'mod_3_3',
        title: 'Module 3: Meteorological Data Visualization with Cartopy & MetPy',
        description: 'Creating publication-grade synoptic maps, streamlines, geopotential height contours, and Skew-T / Tephigrams.',
        order: 3,
        lessons: [
          {
            id: 'les_3_3_1',
            title: '3.1 Generating 850 hPa Wind & Moisture Maps',
            description: 'Using Cartopy PlateCarree projections, coastlines, Indian state boundaries, and MetPy units.',
            order: 1,
            duration: '40 mins',
            type: 'article',
            contentBody: `### Cartopy & MetPy Synoptic Visualization\n\n**Prototype Demo Content — Not Official IMD Material.**\n\n\`\`\`python\nimport matplotlib.pyplot as plt\nimport cartopy.crs as ccrs\nimport cartopy.feature as cfeature\nfrom metpy.units import units\n\nfig = plt.figure(figsize=(10, 8))\nax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())\nax.set_extent([65, 98, 5, 38], crs=ccrs.PlateCarree())\nax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=1.2)\nax.add_feature(cfeature.BORDERS, linestyle=':')\nax.set_title("850 hPa Wind Flow & Moisture Flux - IMD Model Output")\nplt.show()\n\`\`\``,
          },
        ],
      },
      {
        id: 'mod_3_4',
        title: 'Module 4: Automated Weather Analysis Pipelines',
        description: 'Building end-to-end cron pipelines to ingest AWS telemetry, compute heavy rainfall thresholds, and send alerts.',
        order: 4,
        lessons: [
          {
            id: 'les_3_4_1',
            title: '4.1 Automated Extreme Weather Classification and Reporting',
            description: 'Automating IMD heavy rainfall alerts (Heavy: 64.5-115.5mm, Very Heavy: 115.6-204.4mm, Extremely Heavy: >204.4mm).',
            order: 1,
            duration: '30 mins',
            type: 'article',
            contentBody: `### Automated Weather Threshold Alert Engine\n\n**Prototype Demo Content — Not Official IMD Material.**\n\nImplements standard IMD rainfall classification criteria:\n- Moderate: 15.6 to 64.4 mm\n- Heavy: 64.5 to 115.5 mm (Yellow Warning)\n- Very Heavy: 115.6 to 204.4 mm (Orange Warning)\n- Extremely Heavy: $\\ge 204.5$ mm (Red Warning)`,
          },
        ],
      },
    ],
  },
];

export const SEED_ASSESSMENTS: IAssessment[] = [
  {
    _id: 'assess_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    trainerId: 'usr_trainer_001',
    trainerName: 'Dr. Rajesh Sharma',
    title: 'Final Certification Assessment: Weather Forecasting Fundamentals',
    description:
      'Comprehensive MCQ assessment evaluating knowledge of atmospheric dynamics, synoptic chart symbols, observation standards, and tropical forecasting techniques.',
    durationMinutes: 20,
    totalMarks: 5,
    passingPercentage: 60,
    status: 'published',
    createdAt: '2026-01-25T12:00:00Z',
    questions: [
      {
        id: 'q_1_1',
        questionText: 'What is the average standard environmental temperature lapse rate in the troposphere?',
        options: ['9.8 °C per kilometer', '6.5 °C per kilometer', '3.2 °C per kilometer', '1.0 °C per kilometer'],
        correctAnswerIndex: 1,
        explanation: 'The International Standard Atmosphere defines the tropospheric average environmental lapse rate as 6.5 °C/km (approx 0.65 °C per 100 meters).',
        marks: 1,
      },
      {
        id: 'q_1_2',
        questionText: 'In the Northern Hemisphere, which direction does the Coriolis force deflect moving air parcels?',
        options: [
          'Directly towards the equator',
          'To the left of the direction of motion',
          'To the right of the direction of motion',
          'Directly upward into the stratosphere',
        ],
        correctAnswerIndex: 2,
        explanation: 'Due to Earth\'s counterclockwise rotation, the Coriolis force deflects air parcels to their right in the Northern Hemisphere and to their left in the Southern Hemisphere.',
        marks: 1,
      },
      {
        id: 'q_1_3',
        questionText: 'At standard IMD surface meteorological observatories, what is the standard height of a Stevenson Screen thermometer bulb above the ground?',
        options: ['0.5 meters', '1.25 to 1.5 meters', '3.0 meters', '5.0 meters'],
        correctAnswerIndex: 1,
        explanation: 'WMO and IMD standard station guidelines mandate thermometer bulbs inside the double-louvered Stevenson Screen to be situated between 1.25 and 1.5 meters above natural turf ground.',
        marks: 1,
      },
      {
        id: 'q_1_4',
        questionText: 'What does a high CAPE (Convective Available Potential Energy) value exceeding 2000 J/kg on a Tephigram signify?',
        options: [
          'Dry, stable atmosphere with no cloud formation',
          'High potential for severe convective thunderstorms and squall lines',
          'Presence of dense radiation fog',
          'Persistent stratospheric ozone depletion',
        ],
        correctAnswerIndex: 1,
        explanation: 'CAPE measures positive buoyant energy available to an ascending air parcel. Values > 2000 J/kg indicate strong atmospheric instability favoring severe thunderstorms.',
        marks: 1,
      },
      {
        id: 'q_1_5',
        questionText: 'According to IMD criteria, 24-hour rainfall accumulation of 150.0 mm at a station is officially categorized as:',
        options: ['Moderate Rain', 'Heavy Rain', 'Very Heavy Rain', 'Extremely Heavy Rain'],
        correctAnswerIndex: 2,
        explanation: 'IMD rainfall classification: 64.5 - 115.5 mm is Heavy, 115.6 - 204.4 mm is Very Heavy, and >= 204.5 mm is Extremely Heavy.',
        marks: 1,
      },
    ],
  },
  {
    _id: 'assess_002',
    courseId: 'course_002',
    courseTitle: 'Satellite Meteorology',
    trainerId: 'usr_trainer_002',
    trainerName: 'Dr. Ananya Sen',
    title: 'Evaluation Exam: Satellite Meteorology & INSAT Payloads',
    description: 'Assessment covering geostationary orbits, infrared brightness temperatures, and Dvorak cyclone analysis.',
    durationMinutes: 20,
    totalMarks: 4,
    passingPercentage: 60,
    status: 'published',
    createdAt: '2026-02-15T10:00:00Z',
    questions: [
      {
        id: 'q_2_1',
        questionText: 'What is the approximate altitude of a Geostationary Earth Orbit (GEO) meteorological satellite?',
        options: ['800 km', '12,000 km', '35,786 km', '100,000 km'],
        correctAnswerIndex: 2,
        explanation: 'Geostationary satellites orbit at 35,786 km above Earth equator where orbital period exactly matches Earth rotational day.',
        marks: 1,
      },
      {
        id: 'q_2_2',
        questionText: 'Which INSAT-3DR thermal channel is primary for detecting deep convective cloud tops through cloud-top brightness temperature?',
        options: ['TIR1 (10.8 micrometers)', 'Visible channel (0.65 micrometers)', 'Shortwave Infrared (1.6 micrometers)', 'Solar Albedo band'],
        correctAnswerIndex: 0,
        explanation: 'The Thermal Infrared 1 (TIR1) atmospheric window (~10.8 um) measures emitted thermal radiation to calculate cloud top temperature day and night.',
        marks: 1,
      },
      {
        id: 'q_2_3',
        questionText: 'What does the Dvorak Tropical Cyclone Classification Technique primarily measure from satellite cloud patterns?',
        options: ['Ocean salinity gradient', 'Estimated central pressure deficit and maximum sustained surface wind', 'Geomagnetic disturbance', 'Rainwater pH balance'],
        correctAnswerIndex: 1,
        explanation: 'The Dvorak technique relates subjective visual and IR cloud patterns into T-numbers corresponding to central pressure and peak sustained wind speeds.',
        marks: 1,
      },
      {
        id: 'q_2_4',
        questionText: 'Why is the Water Vapor (WV, 6.7 micrometer) channel capable of visualizing upper-tropospheric features even in cloudless areas?',
        options: [
          'It detects solar ultraviolet backscattering',
          'It senses mid-to-upper tropospheric moisture absorption/emission irrespective of cloud condensation',
          'It relies on ocean surface glitter',
          'It is an active radar pulse transceiver',
        ],
        correctAnswerIndex: 1,
        explanation: 'The 6.7 um band sits in a strong water vapor absorption spectrum, measuring radiation emitted by moisture in the 300-600 hPa layer.',
        marks: 1,
      },
    ],
  },
  {
    _id: 'assess_003',
    courseId: 'course_003',
    courseTitle: 'Python for Meteorological Data Analysis',
    trainerId: 'usr_trainer_003',
    trainerName: 'Dr. Vikram Verma',
    title: 'Technical Assessment: Python & Scientific Atmospheric Computing',
    description: 'Covers NetCDF, Xarray coordinates, MetPy calculations, and geospatial plotting for IMD datasets.',
    durationMinutes: 20,
    totalMarks: 4,
    passingPercentage: 60,
    status: 'published',
    createdAt: '2026-02-25T11:00:00Z',
    questions: [
      {
        id: 'q_3_1',
        questionText: 'Which Python library is the standard multi-dimensional labeled array container specifically optimized for NetCDF and GRIB meteorological data?',
        options: ['Pygame', 'Xarray', 'Flask', 'BeautifulSoup'],
        correctAnswerIndex: 1,
        explanation: 'Xarray introduces labeled dimensions, coordinates, and attributes onto NumPy arrays, matching the NetCDF scientific data model seamlessly.',
        marks: 1,
      },
      {
        id: 'q_3_2',
        questionText: 'In MetPy, why is it critical to attach units to numerical variables before performing atmospheric calculations?',
        options: [
          'To prevent font rendering glitches in matplotlib',
          'To enable automatic dimensional unit checking and mathematical unit conversion (e.g., Kelvin to Celsius, Pa to hPa)',
          'To speed up CPU processing using GPU cuda kernels',
          'To encrypt the meteorological data arrays',
        ],
        correctAnswerIndex: 1,
        explanation: 'MetPy uses the Pint units package to guarantee dimensional consistency and prevent catastrophic unit mismatch errors in thermodynamic formulas.',
        marks: 1,
      },
      {
        id: 'q_3_3',
        questionText: 'Which Cartopy coordinate reference system (CRS) is standard for plotting unprojected latitude-longitude gridded datasets?',
        options: ['ccrs.Orthographic()', 'ccrs.PlateCarree()', 'ccrs.Robinson()', 'ccrs.Mercator()'],
        correctAnswerIndex: 1,
        explanation: 'PlateCarree is an equidistant cylindrical projection where coordinates map directly to standard geographic latitude and longitude degrees.',
        marks: 1,
      },
      {
        id: 'q_3_4',
        questionText: 'When processing daily rainfall with missing records represented as -999.0 in NumPy, which function safely calculates station mean ignoring invalid values?',
        options: ['np.mean()', 'np.nanmean() after replacing -999.0 with np.nan', 'np.sum() / 365', 'np.median()'],
        correctAnswerIndex: 1,
        explanation: 'Replacing sentinel values with np.nan and utilizing np.nanmean() calculates the correct arithmetic average omitting missing stations.',
        marks: 1,
      },
    ],
  },
];

export const SEED_ENROLLMENTS: IEnrollment[] = [
  {
    _id: 'enr_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_001',
    status: 'completed',
    progressPercentage: 100,
    completedLessonIds: ['les_1_1_1', 'les_1_1_2', 'les_1_2_1', 'les_1_2_2', 'les_1_3_1', 'les_1_4_1'],
    enrolledAt: '2026-02-02T10:00:00Z',
    completedAt: '2026-02-28T16:45:00Z',
    lastAccessedAt: '2026-03-01T12:00:00Z',
    assessmentAttemptId: 'att_001',
    assessmentScore: 100,
    certificateId: 'IMD-CC-2026-09284',
  },
  {
    _id: 'enr_002',
    courseId: 'course_002',
    courseTitle: 'Satellite Meteorology',
    traineeId: 'usr_trainee_001',
    status: 'in-progress',
    progressPercentage: 50,
    completedLessonIds: ['les_2_1_1', 'les_2_2_1'],
    enrolledAt: '2026-03-05T09:30:00Z',
    lastAccessedAt: '2026-03-12T11:15:00Z',
  },
];

export const SEED_CERTIFICATES: ICertificate[] = [
  {
    _id: 'cert_001',
    certificateId: 'IMD-CC-2026-09284',
    traineeId: 'usr_trainee_001',
    traineeName: 'Pooja Iyer',
    traineeDepartment: 'Regional Meteorological Centre, Mumbai',
    courseId: 'course_001',
    courseName: 'Weather Forecasting Fundamentals',
    trainerName: 'Dr. Rajesh Sharma',
    issueDate: '2026-02-28T16:50:00Z',
    completionDate: '2026-02-28T16:45:00Z',
    scorePercentage: 100,
    verificationCode: 'VER-IMD-78942-WFF',
  },
];

export const SEED_ANNOUNCEMENTS: IAnnouncement[] = [
  {
    _id: 'ann_001',
    title: 'National Pre-Monsoon Capacity Building Workshop 2026',
    content:
      'The Director General of Meteorology announces the mandatory pre-monsoon capacity building drive. All Scientific Assistants and Operational Forecasters at coastal and river basin stations must complete the Satellite Meteorology and Doppler Radar Refresher courses before April 15, 2026.',
    type: 'urgent',
    targetRole: 'all',
    author: 'Directorate General, IMD HQ New Delhi',
    priority: 'high',
    createdAt: '2026-03-01T09:00:00Z',
  },
  {
    _id: 'ann_002',
    title: 'New Competency Mapping Framework Deployed',
    content:
      'Capacity Connect portal now automatically maps competency scores across 7 core meteorological domains and highlights targeted skill gaps for personnel upskilling and career progression.',
    type: 'achievement',
    targetRole: 'all',
    author: 'IMD Central Training Division, Pune',
    priority: 'normal',
    createdAt: '2026-02-20T11:30:00Z',
  },
  {
    _id: 'ann_003',
    title: 'Trainer Competency Matching System Operational',
    content:
      'Divisional heads can now calculate transparent competency matches when assigning certified trainers to regional training institutes across New Delhi, Pune, Kolkata, Chennai, Guwahati, and Mumbai.',
    type: 'general',
    targetRole: 'trainer',
    author: 'Capacity Assessment Directorate',
    priority: 'normal',
    createdAt: '2026-02-10T14:00:00Z',
  },
];

export const SEED_FEEDBACKS: IFeedback[] = [
  {
    _id: 'fb_001',
    courseId: 'course_001',
    courseTitle: 'Weather Forecasting Fundamentals',
    traineeId: 'usr_trainee_001',
    traineeName: 'Pooja Iyer',
    rating: 5,
    comments:
      'Outstanding modules! The explanation of thermodynamic tephigram diagrams, CAPE analysis, and severe weather warning criteria directly helped my shift duties at RMC Mumbai.',
    createdAt: '2026-03-01T17:00:00Z',
  },
];
