import { NextResponse } from 'next/server';
import {
  MAJOR_INDIA_CITIES,
  ICityWeatherData,
  IWeatherAlert,
  IRealtimeWeatherResponse,
  getWindCompass,
  decodeWmoWeatherCode,
} from '@/lib/weather-service';

// In-memory cache for 5-minute aggregation to avoid excessive requests
let cachedWeatherData: IRealtimeWeatherResponse | null = null;
let lastCacheFetchTime = 0;
const CACHE_TTL_MS = 4 * 60 * 1000; // 4 minutes

// Robust fallback synthetic dataset in case outbound internet or weather API is restricted
function getDemoFallbackDataset(): IRealtimeWeatherResponse {
  const now = new Date();
  const timeStr = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true });

  const fallbackCities: ICityWeatherData[] = [
    {
      id: 'delhi',
      name: 'Delhi',
      state: 'NCT Delhi',
      region: 'NORTH',
      lat: 28.6139,
      lng: 77.2090,
      x: 32.5,
      y: 30.5,
      temperature: 28.2,
      feelsLike: 31.4,
      relativeHumidity: 68,
      windSpeed: 8.5,
      windDirection: 290,
      windDirectionCompass: 'WNW',
      pressureMsl: 1009.4,
      precipitation: 0.0,
      cloudCover: 15,
      visibility: 8.5,
      weatherCode: 1,
      condition: 'Mainly Clear',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'srinagar',
      name: 'Srinagar',
      state: 'Jammu & Kashmir',
      region: 'NORTH',
      lat: 34.0837,
      lng: 74.7973,
      x: 25.1,
      y: 13.8,
      temperature: 17.5,
      feelsLike: 17.1,
      relativeHumidity: 62,
      windSpeed: 6.2,
      windDirection: 310,
      windDirectionCompass: 'NW',
      pressureMsl: 1014.2,
      precipitation: 0.0,
      cloudCover: 30,
      visibility: 10.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'chandigarh',
      name: 'Chandigarh',
      state: 'Punjab / Haryana',
      region: 'NORTH',
      lat: 30.7333,
      lng: 76.7794,
      x: 31.2,
      y: 24.0,
      temperature: 27.6,
      feelsLike: 29.8,
      relativeHumidity: 64,
      windSpeed: 7.0,
      windDirection: 300,
      windDirectionCompass: 'WNW',
      pressureMsl: 1010.1,
      precipitation: 0.0,
      cloudCover: 20,
      visibility: 9.0,
      weatherCode: 1,
      condition: 'Mainly Clear',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'jaipur',
      name: 'Jaipur',
      state: 'Rajasthan',
      region: 'NORTH',
      lat: 26.9124,
      lng: 75.7873,
      x: 28.1,
      y: 35.6,
      temperature: 30.8,
      feelsLike: 33.5,
      relativeHumidity: 55,
      windSpeed: 11.2,
      windDirection: 270,
      windDirectionCompass: 'W',
      pressureMsl: 1008.8,
      precipitation: 0.0,
      cloudCover: 10,
      visibility: 10.0,
      weatherCode: 0,
      condition: 'Clear Sky',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'lucknow',
      name: 'Lucknow',
      state: 'Uttar Pradesh',
      region: 'NORTH',
      lat: 26.8467,
      lng: 80.9462,
      x: 44.0,
      y: 35.8,
      temperature: 29.1,
      feelsLike: 33.2,
      relativeHumidity: 74,
      windSpeed: 6.4,
      windDirection: 110,
      windDirectionCompass: 'ESE',
      pressureMsl: 1008.2,
      precipitation: 0.0,
      cloudCover: 40,
      visibility: 7.5,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'mumbai',
      name: 'Mumbai',
      state: 'Maharashtra',
      region: 'WEST',
      lat: 19.0760,
      lng: 72.8777,
      x: 19.2,
      y: 59.5,
      temperature: 28.6,
      feelsLike: 33.8,
      relativeHumidity: 82,
      windSpeed: 14.8,
      windDirection: 240,
      windDirectionCompass: 'WSW',
      pressureMsl: 1010.8,
      precipitation: 1.2,
      cloudCover: 75,
      visibility: 6.0,
      weatherCode: 61,
      condition: 'Passing Showers',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'pune',
      name: 'Pune',
      state: 'Maharashtra',
      region: 'WEST',
      lat: 18.5204,
      lng: 73.8567,
      x: 22.2,
      y: 61.2,
      temperature: 26.4,
      feelsLike: 28.5,
      relativeHumidity: 78,
      windSpeed: 12.0,
      windDirection: 230,
      windDirectionCompass: 'SW',
      pressureMsl: 1011.5,
      precipitation: 0.4,
      cloudCover: 60,
      visibility: 8.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'ahmedabad',
      name: 'Ahmedabad',
      state: 'Gujarat',
      region: 'WEST',
      lat: 23.0225,
      lng: 72.5714,
      x: 18.2,
      y: 47.5,
      temperature: 31.4,
      feelsLike: 35.0,
      relativeHumidity: 62,
      windSpeed: 10.5,
      windDirection: 250,
      windDirectionCompass: 'WSW',
      pressureMsl: 1009.6,
      precipitation: 0.0,
      cloudCover: 25,
      visibility: 9.0,
      weatherCode: 1,
      condition: 'Mainly Clear',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'surat',
      name: 'Surat',
      state: 'Gujarat',
      region: 'WEST',
      lat: 21.1702,
      lng: 72.8311,
      x: 19.0,
      y: 53.1,
      temperature: 29.8,
      feelsLike: 34.2,
      relativeHumidity: 76,
      windSpeed: 13.0,
      windDirection: 245,
      windDirectionCompass: 'WSW',
      pressureMsl: 1010.2,
      precipitation: 0.0,
      cloudCover: 45,
      visibility: 8.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'bhopal',
      name: 'Bhopal',
      state: 'Madhya Pradesh',
      region: 'CENTRAL',
      lat: 23.2599,
      lng: 77.4126,
      x: 33.1,
      y: 46.8,
      temperature: 28.0,
      feelsLike: 30.6,
      relativeHumidity: 66,
      windSpeed: 8.0,
      windDirection: 280,
      windDirectionCompass: 'W',
      pressureMsl: 1009.1,
      precipitation: 0.0,
      cloudCover: 35,
      visibility: 8.5,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'nagpur',
      name: 'Nagpur',
      state: 'Maharashtra',
      region: 'CENTRAL',
      lat: 21.1458,
      lng: 79.0882,
      x: 38.3,
      y: 53.2,
      temperature: 29.5,
      feelsLike: 33.1,
      relativeHumidity: 70,
      windSpeed: 7.5,
      windDirection: 260,
      windDirectionCompass: 'W',
      pressureMsl: 1009.8,
      precipitation: 0.0,
      cloudCover: 40,
      visibility: 9.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'indore',
      name: 'Indore',
      state: 'Madhya Pradesh',
      region: 'CENTRAL',
      lat: 22.7196,
      lng: 75.8577,
      x: 28.3,
      y: 48.4,
      temperature: 28.4,
      feelsLike: 31.0,
      relativeHumidity: 65,
      windSpeed: 9.2,
      windDirection: 275,
      windDirectionCompass: 'W',
      pressureMsl: 1009.3,
      precipitation: 0.0,
      cloudCover: 30,
      visibility: 9.0,
      weatherCode: 1,
      condition: 'Mainly Clear',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'bengaluru',
      name: 'Bengaluru',
      state: 'Karnataka',
      region: 'SOUTH',
      lat: 12.9716,
      lng: 77.5946,
      x: 33.7,
      y: 78.1,
      temperature: 23.8,
      feelsLike: 25.1,
      relativeHumidity: 86,
      windSpeed: 9.5,
      windDirection: 75,
      windDirectionCompass: 'ENE',
      pressureMsl: 1013.8,
      precipitation: 0.6,
      cloudCover: 88,
      visibility: 7.0,
      weatherCode: 51,
      condition: 'Light Drizzle',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'hyderabad',
      name: 'Hyderabad',
      state: 'Telangana',
      region: 'SOUTH',
      lat: 17.3850,
      lng: 78.4867,
      x: 36.4,
      y: 64.7,
      temperature: 27.2,
      feelsLike: 29.8,
      relativeHumidity: 75,
      windSpeed: 8.8,
      windDirection: 130,
      windDirectionCompass: 'SE',
      pressureMsl: 1011.0,
      precipitation: 0.0,
      cloudCover: 50,
      visibility: 8.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'chennai',
      name: 'Chennai',
      state: 'Tamil Nadu',
      region: 'SOUTH',
      lat: 13.0827,
      lng: 80.2707,
      x: 41.9,
      y: 77.8,
      temperature: 30.5,
      feelsLike: 36.2,
      relativeHumidity: 74,
      windSpeed: 9.0,
      windDirection: 160,
      windDirectionCompass: 'SSE',
      pressureMsl: 1009.9,
      precipitation: 0.0,
      cloudCover: 45,
      visibility: 10.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'kochi',
      name: 'Kochi',
      state: 'Kerala',
      region: 'SOUTH',
      lat: 9.9312,
      lng: 76.2673,
      x: 29.6,
      y: 87.4,
      temperature: 27.5,
      feelsLike: 31.8,
      relativeHumidity: 88,
      windSpeed: 10.4,
      windDirection: 250,
      windDirectionCompass: 'WSW',
      pressureMsl: 1012.2,
      precipitation: 2.5,
      cloudCover: 90,
      visibility: 6.0,
      weatherCode: 61,
      condition: 'Rain Showers',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'kolkata',
      name: 'Kolkata',
      state: 'West Bengal',
      region: 'EAST',
      lat: 22.5726,
      lng: 88.3639,
      x: 66.8,
      y: 48.9,
      temperature: 29.4,
      feelsLike: 35.8,
      relativeHumidity: 80,
      windSpeed: 6.5,
      windDirection: 180,
      windDirectionCompass: 'S',
      pressureMsl: 1007.8,
      precipitation: 0.0,
      cloudCover: 35,
      visibility: 8.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'bhubaneswar',
      name: 'Bhubaneswar',
      state: 'Odisha',
      region: 'EAST',
      lat: 20.2961,
      lng: 85.8245,
      x: 59.0,
      y: 55.8,
      temperature: 28.8,
      feelsLike: 34.0,
      relativeHumidity: 82,
      windSpeed: 8.2,
      windDirection: 170,
      windDirectionCompass: 'S',
      pressureMsl: 1008.5,
      precipitation: 0.8,
      cloudCover: 65,
      visibility: 7.5,
      weatherCode: 2,
      condition: 'Cloudy with Light Rain',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'patna',
      name: 'Patna',
      state: 'Bihar',
      region: 'EAST',
      lat: 25.5941,
      lng: 85.1376,
      x: 56.9,
      y: 39.7,
      temperature: 28.6,
      feelsLike: 32.5,
      relativeHumidity: 72,
      windSpeed: 5.5,
      windDirection: 90,
      windDirectionCompass: 'E',
      pressureMsl: 1008.0,
      precipitation: 0.0,
      cloudCover: 40,
      visibility: 8.5,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'ranchi',
      name: 'Ranchi',
      state: 'Jharkhand',
      region: 'EAST',
      lat: 23.3441,
      lng: 85.3096,
      x: 57.4,
      y: 46.5,
      temperature: 25.5,
      feelsLike: 27.2,
      relativeHumidity: 76,
      windSpeed: 7.2,
      windDirection: 140,
      windDirectionCompass: 'SE',
      pressureMsl: 1009.0,
      precipitation: 0.0,
      cloudCover: 50,
      visibility: 9.0,
      weatherCode: 2,
      condition: 'Partly Cloudy',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
    {
      id: 'guwahati',
      name: 'Guwahati',
      state: 'Assam',
      region: 'NORTHEAST',
      lat: 26.1445,
      lng: 91.7362,
      x: 77.2,
      y: 38.0,
      temperature: 26.8,
      feelsLike: 30.2,
      relativeHumidity: 84,
      windSpeed: 5.0,
      windDirection: 60,
      windDirectionCompass: 'ENE',
      pressureMsl: 1008.4,
      precipitation: 1.8,
      cloudCover: 80,
      visibility: 7.0,
      weatherCode: 61,
      condition: 'Light Rain',
      isDay: true,
      observationTime: `Today, ${timeStr} IST`,
    },
  ];

  const alerts: IWeatherAlert[] = [
    {
      id: 'alert_01',
      severity: 'WATCH',
      title: 'Southwest Monsoon Withdrawal Watch',
      area: 'Northwest India & West Rajasthan',
      startTime: 'Today 08:30 IST',
      endTime: 'Tomorrow 17:30 IST',
      source: 'National Weather Forecasting Centre',
      description: 'Conditions continue to be favorable for further withdrawal of Southwest Monsoon across Rajasthan and adjoining areas.',
    },
    {
      id: 'alert_02',
      severity: 'ALERT',
      title: 'Heavy Rainfall Warning',
      area: 'Coastal Karnataka, Konkan & Goa',
      startTime: 'Today 12:00 IST',
      endTime: 'Tomorrow 12:00 IST',
      source: 'Regional Meteorological Centre Mumbai',
      description: 'Isolated heavy to very heavy rainfall accompanied by gusty winds expected over coastal belts.',
    },
  ];

  return {
    success: true,
    isLive: false,
    source: 'Demonstration Meteorological Dataset',
    lastUpdated: now.toISOString(),
    cities: fallbackCities,
    alerts,
  };
}

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const forceDemo = searchParams.get('mode') === 'demo';

    if (forceDemo) {
      return NextResponse.json(getDemoFallbackDataset());
    }

    // Check cache
    const now = Date.now();
    if (cachedWeatherData && now - lastCacheFetchTime < CACHE_TTL_MS) {
      return NextResponse.json(cachedWeatherData);
    }

    // Build batch Open-Meteo URL for all 21 Indian Cities in ONE fast query
    const latList = MAJOR_INDIA_CITIES.map((c) => c.lat.toFixed(4)).join(',');
    const lngList = MAJOR_INDIA_CITIES.map((c) => c.lng.toFixed(4)).join(',');

    const apiUrl = `https://api.open-meteo.com/v1/forecast?latitude=${latList}&longitude=${lngList}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,weather_code,cloud_cover,pressure_msl,wind_speed_10m,wind_direction_10m,visibility,is_day&timezone=Asia%2FKolkata`;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 7000); // 7s timeout

    const res = await fetch(apiUrl, {
      signal: controller.signal,
      headers: { 'User-Agent': 'MeghSetu-IMD-Portal/1.0' },
      next: { revalidate: 240 },
    });
    clearTimeout(timeoutId);

    if (!res.ok) {
      throw new Error(`Open-Meteo API returned status ${res.status}`);
    }

    const data = await res.json();
    const items = Array.isArray(data) ? data : [data];

    const timestampStr = new Date().toLocaleTimeString('en-IN', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
    });

    const parsedCities: ICityWeatherData[] = MAJOR_INDIA_CITIES.map((city, idx) => {
      const entry = items[idx]?.current || {};
      const temp = typeof entry.temperature_2m === 'number' ? entry.temperature_2m : 28.0;
      const feels = typeof entry.apparent_temperature === 'number' ? entry.apparent_temperature : temp + 2.5;
      const rh = typeof entry.relative_humidity_2m === 'number' ? entry.relative_humidity_2m : 70;
      const windSpeed = typeof entry.wind_speed_10m === 'number' ? entry.wind_speed_10m : 10.0;
      const windDir = typeof entry.wind_direction_10m === 'number' ? entry.wind_direction_10m : 240;
      const pressure = typeof entry.pressure_msl === 'number' ? entry.pressure_msl : 1010.0;
      const precipitation = typeof entry.precipitation === 'number' ? entry.precipitation : 0.0;
      const cloudCover = typeof entry.cloud_cover === 'number' ? entry.cloud_cover : 40;
      const visKm = typeof entry.visibility === 'number' ? Math.round(entry.visibility / 100) / 10 : 8.0;
      const code = typeof entry.weather_code === 'number' ? entry.weather_code : 0;
      const isDay = entry.is_day !== 0;

      return {
        id: city.id,
        name: city.name,
        state: city.state,
        region: city.region,
        lat: city.lat,
        lng: city.lng,
        x: city.x,
        y: city.y,
        temperature: Math.round(temp * 10) / 10,
        feelsLike: Math.round(feels * 10) / 10,
        relativeHumidity: Math.round(rh),
        windSpeed: Math.round(windSpeed * 10) / 10,
        windDirection: Math.round(windDir),
        windDirectionCompass: getWindCompass(windDir),
        pressureMsl: Math.round(pressure * 10) / 10,
        precipitation: Math.round(precipitation * 10) / 10,
        cloudCover: Math.round(cloudCover),
        visibility: visKm,
        weatherCode: code,
        condition: decodeWmoWeatherCode(code),
        isDay,
        observationTime: `Live, ${timestampStr} IST`,
      };
    });

    const alerts: IWeatherAlert[] = [
      {
        id: 'alert_01',
        severity: 'ALERT',
        title: 'Coastal Weather Advisory',
        area: 'Konkan, Goa & Coastal Karnataka',
        startTime: `Today ${timestampStr} IST`,
        endTime: 'Next 24 Hours',
        source: 'Automated Synoptic Telemetry',
        description: 'Moisture incursion from Arabian Sea generating convective rainbands and moderate to gusty winds.',
      },
    ];

    const responsePayload: IRealtimeWeatherResponse = {
      success: true,
      isLive: true,
      source: 'Open-Meteo High-Resolution Numerical Forecast API',
      lastUpdated: new Date().toISOString(),
      cities: parsedCities,
      alerts,
    };

    cachedWeatherData = responsePayload;
    lastCacheFetchTime = now;

    return NextResponse.json(responsePayload);
  } catch (error: any) {
    console.warn('Real-time weather API query failed, serving fallback:', error.message);
    // If cache exists, serve stale cache with delayed flag
    if (cachedWeatherData) {
      return NextResponse.json({
        ...cachedWeatherData,
        isLive: false,
        source: `${cachedWeatherData.source} (Cached)`,
      });
    }
    return NextResponse.json(getDemoFallbackDataset());
  }
}
